--Document Type Setup
select TYPE_ID,TYPE_NAME,TYPE_DESC, INSERT_BY, INSERT_DATE, INSERT_TIME, UPDATE_BY, UPDATE_DATE, UPDATE_TIME
from DF_TYPE;

--Head of Department Setup
select ID, EMPCODE, E_NAME, DEPT_NAME, UNIT
from DEPAT_HEAD; 

--Document forwarding Sequence Setup
select SQ_ID,TYPE_ID,UNIT_ID,DEPT_ID,L1_EMPCODE,L2_EMPCODE,L3_EMPCODE,L4_EMPCODE,L5_EMPCODE,L6_EMPCODE,L7_EMPCODE,L8_EMPCODE,L9_EMPCODE,L10_EMPCODE,L11_EMPCODE,L12_EMPCODE,IS_ACTIVE,INSERT_BY,INSERT_DATE,INSERT_TIME,UPDATE_BY,UPDATE_DATE,UPDATE_TIME,ITEM_ID,CATEGORY_ID,ENT_BY,ENT_DATE,UPD_BY,UPD_DATE
from DF_SEQUENCE;

--Procuremnent Item Setup with Head of Department Details
select ID, ITEM_ID, ITEM_NAME, DEPT_NAME, EMPCODE, CREATE_BY, UPDATE_BY, CCODE 
from PUR_ITEM;


--Document Forwarding Master
select DF_SLNO,DF_TRAN_NO,TYPE_ID,EMPCODE,DF_TITE,DF_DETAIL,UNIT_ID,DEPT_ID,SQ_ID,L0_EMPCODE,L1_EMPCODE,L2_EMPCODE,L3_EMPCODE,L4_EMPCODE,L5_EMPCODE,L6_EMPCODE,L7_EMPCODE,L8_EMPCODE,L9_EMPCODE,L10_EMPCODE,L11_EMPCODE,L12_EMPCODE,L0_COMMENT,L1_COMMENT,L2_COMMENT,L3_COMMENT,L4_COMMENT,L5_COMMENT,L6_COMMENT,L7_COMMENT,L8_COMMENT,L9_COMMENT,L10_COMMENT,L11_COMMENT,L12_COMMENT,L0_TYPE,L1_TYPE,L2_TYPE,L3_TYPE,L4_TYPE,L5_TYPE,L6_TYPE,L7_TYPE,L8_TYPE,L9_TYPE,L10_TYPE,L11_TYPE,L12_TYPE,L0_DATE,L1_DATE,L2_DATE,L3_DATE,L4_DATE,L5_DATE,L6_DATE,L7_DATE,L8_DATE,L9_DATE,L10_DATE,L11_DATE,L12_DATE,STATUS_SL,STATUS_DETAILS,INSERT_BY,INSERT_DATE,INSERT_TIME,UPDATE_BY,UPDATE_DATE,UPDATE_TIME,DF_TRAN_DATE,DF_STATUS,CATEGORY_ID,ITEM_ID    
from DF_MASTER;



/* Formatted on 9/7/2025 6:17:02 PM (QP5 v5.362) */
CREATE TABLE doc_type
(
    type_id      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    type_name    VARCHAR2 (20 BYTE),
    type_desc    VARCHAR2 (150 BYTE),
    ent_by       VARCHAR2 (20 BYTE),
    ent_date     DATE,
    upd_by       VARCHAR2 (20 BYTE),
    upd_date     DATE,
    ccode        VARCHAR2 (20 BYTE),
    com_id       NUMBER
);

CREATE TABLE dept_head
(
    id             NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    hod_empcode    VARCHAR2 (15 BYTE),
    e_name         VARCHAR2 (150 BYTE),
    dept_name      VARCHAR2 (100 BYTE),
    ent_by         VARCHAR2 (20 BYTE),
    ent_date       DATE,
    upd_by         VARCHAR2 (20 BYTE),
    upd_date       DATE,
    ccode          VARCHAR2 (20 BYTE),
    com_id         NUMBER
);
/

CREATE TABLE pro_item
(
    item_id        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    item_name      VARCHAR2 (100 BYTE),
    dept_name      VARCHAR2 (200 BYTE),
    exp_empcode    VARCHAR2 (30 BYTE),
    unitid         VARCHAR2 (30 BYTE),
    ent_by         VARCHAR2 (20 BYTE),
    ent_date       DATE,
    upd_by         VARCHAR2 (20 BYTE),
    upd_date       DATE,
    ccode          VARCHAR2 (20 BYTE),
    com_id         NUMBER
);