/* Formatted on 31/Aug/24 3:38:12 PM (QP5 v5.362) */
SELECT empcode,
       E_NAME,
       web_password,
       EMP_STATUS
  FROM EMP_SEP310824
 WHERE empcode IN ('%%',
                   '%%',
                   '%%',
                   '%%',
                   '%%',
                   '%%',
                   '%%',
                   '%%',
                   '%%',
                   '%%',
                   '%%',
                   '%%');
                   