CREATE OR REPLACE FORCE VIEW IPIHR.EMP_ALL_V
(
    EMPCODE,
    NAME,
    DEPARTMENT_NAME,
    SERVICE,
    RATE,
    OTRATE,
    NIGHTAL,
    ATTBONUS,
    FEBONUS,
    REMARKS,
    JOIN_DATE,
    SHIFT_ID,
    SHIFT_NAME,
    SHIFT_START_DATE,
    BADGENUMBER,
    SHIFT_TRACE_ID,
    DP_CODE,
    EMP_STATUS,
    SEPARATE_DATE,
    DP_NAME,
    DESIG_NAME,
    DL_RATE,
    OT_RATE,
    NA_RATE,
    IS_OT,
    EMP_TYPE,
    SALARYGRADE,
    DEPT_NAME_2
)
BEQUEATH DEFINER
AS
    SELECT empcode,
           e_name           NAME,
           department_name,
           service,
           0                rate,
           otrate,
           0                nightal,
           0                attbonus,
           0                febonus,
           remarks,
           join_date,
           shift_id,
           shift_name,
           shift_start_date,
           badgenumber,
           shift_trace_id,
           dp_code_att,
           emp_status,
           ter_date         separate_date,
           location_att     dp_name,
           desig_name,
           dl_rate,
           ot_rate,
           na_rate,
           is_ot,
           'PE'             emp_type,
           salarygrade,
           dept_name_2
      FROM emp
     WHERE emp_status = 'N';
