--HR_EMPCHANGE
--HR_EMPINCR_DET
--HR_REVIEW_HISTORY
--HR_EMPSALSTRUCTURE
SET DEFINE OFF;
Insert into HR_EMPINCR_DET
   (REFNO, LTYPE, SLNO, EMPCODE, YEAROFSTRUC, 
    EDATE, TRNDATE, PARTICULAR, DESIGCODE, AMOUNTPRV, 
    AMOUNTCUR, SALPER, YEARMN, PRTCLR_TYPE, HEADCODE, 
    ADDEDBY, ADD_COMP_NAME, ADD_IPADD, ADD_OSUSER, UPD_COMP_NAME, 
    UPD_IPADD, UPD_OSUSER, UPDATEDDATE, UPDATEDBY, SCALE, 
    DATASOURCE, SALARY_1STEP_BEFORE)
 Values
   ('102202407/79', '102', 1, 'IPI-007001', 2020, 
    NULL, TO_DATE('06/Jul/24', 'DD/MON/YY'), 'Basic Salary', 'GRADE-12', 10800, 
    12075, 12075, 202407, '1', '001', 
    'IPI-006231', NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    'Form', NULL);
Insert into HR_EMPINCR_DET
   (REFNO, LTYPE, SLNO, EMPCODE, YEAROFSTRUC, 
    EDATE, TRNDATE, PARTICULAR, DESIGCODE, AMOUNTPRV, 
    AMOUNTCUR, SALPER, YEARMN, PRTCLR_TYPE, HEADCODE, 
    ADDEDBY, ADD_COMP_NAME, ADD_IPADD, ADD_OSUSER, UPD_COMP_NAME, 
    UPD_IPADD, UPD_OSUSER, UPDATEDDATE, UPDATEDBY, SCALE, 
    DATASOURCE, SALARY_1STEP_BEFORE)
 Values
   ('102202407/79', '102', 5, 'IPI-007001', 2020, 
    NULL, TO_DATE('06/Jul/24', 'DD/MON/YY'), 'House Rent', 'GRADE-12', 8101, 
    9056, 9056, 202407, '1', '005', 
    'IPI-006231', NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    'Form', NULL);
Insert into HR_EMPINCR_DET
   (REFNO, LTYPE, SLNO, EMPCODE, YEAROFSTRUC, 
    EDATE, TRNDATE, PARTICULAR, DESIGCODE, AMOUNTPRV, 
    AMOUNTCUR, SALPER, YEARMN, PRTCLR_TYPE, HEADCODE, 
    ADDEDBY, ADD_COMP_NAME, ADD_IPADD, ADD_OSUSER, UPD_COMP_NAME, 
    UPD_IPADD, UPD_OSUSER, UPDATEDDATE, UPDATEDBY, SCALE, 
    DATASOURCE, SALARY_1STEP_BEFORE)
 Values
   ('102202407/79', '102', 7, 'IPI-007001', 2020, 
    NULL, TO_DATE('06/Jul/24', 'DD/MON/YY'), 'Conveyance  Allow', 'GRADE-12', 2200, 
    2200, 2200, 202407, '1', '007', 
    'IPI-006231', NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    'Form', NULL);
Insert into HR_EMPINCR_DET
   (REFNO, LTYPE, SLNO, EMPCODE, YEAROFSTRUC, 
    EDATE, TRNDATE, PARTICULAR, DESIGCODE, AMOUNTPRV, 
    AMOUNTCUR, SALPER, YEARMN, PRTCLR_TYPE, HEADCODE, 
    ADDEDBY, ADD_COMP_NAME, ADD_IPADD, ADD_OSUSER, UPD_COMP_NAME, 
    UPD_IPADD, UPD_OSUSER, UPDATEDDATE, UPDATEDBY, SCALE, 
    DATASOURCE, SALARY_1STEP_BEFORE)
 Values
   ('102202407/79', '102', 10, 'IPI-007001', 2020, 
    NULL, TO_DATE('06/Jul/24', 'DD/MON/YY'), 'Medical Allowance', 'GRADE-12', 2000, 
    2000, 2000, 202407, '1', '010', 
    'IPI-006231', NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    'Form', NULL);
Insert into HR_EMPINCR_DET
   (REFNO, LTYPE, SLNO, EMPCODE, YEAROFSTRUC, 
    EDATE, TRNDATE, PARTICULAR, DESIGCODE, AMOUNTPRV, 
    AMOUNTCUR, SALPER, YEARMN, PRTCLR_TYPE, HEADCODE, 
    ADDEDBY, ADD_COMP_NAME, ADD_IPADD, ADD_OSUSER, UPD_COMP_NAME, 
    UPD_IPADD, UPD_OSUSER, UPDATEDDATE, UPDATEDBY, SCALE, 
    DATASOURCE, SALARY_1STEP_BEFORE)
 Values
   ('102202407/79', '102', 13, 'IPI-007001', 2020, 
    NULL, TO_DATE('06/Jul/24', 'DD/MON/YY'), 'Co''S  Con. To Pf', 'GRADE-12', 1080, 
    1208, 1208, 202407, '1', '013', 
    'IPI-006231', NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    'Form', NULL);
Insert into HR_EMPINCR_DET
   (REFNO, LTYPE, SLNO, EMPCODE, YEAROFSTRUC, 
    EDATE, TRNDATE, PARTICULAR, DESIGCODE, AMOUNTPRV, 
    AMOUNTCUR, SALPER, YEARMN, PRTCLR_TYPE, HEADCODE, 
    ADDEDBY, ADD_COMP_NAME, ADD_IPADD, ADD_OSUSER, UPD_COMP_NAME, 
    UPD_IPADD, UPD_OSUSER, UPDATEDDATE, UPDATEDBY, SCALE, 
    DATASOURCE, SALARY_1STEP_BEFORE)
 Values
   ('102202407/79', '102', 15, 'IPI-007001', 2020, 
    NULL, TO_DATE('06/Jul/24', 'DD/MON/YY'), 'Dearness Allowance', 'GRADE-12', NULL, 
    1208, 0, 202407, '1', '015', 
    'IPI-006231', NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    'Form', NULL);
Insert into HR_EMPINCR_DET
   (REFNO, LTYPE, SLNO, EMPCODE, YEAROFSTRUC, 
    EDATE, TRNDATE, PARTICULAR, DESIGCODE, AMOUNTPRV, 
    AMOUNTCUR, SALPER, YEARMN, PRTCLR_TYPE, HEADCODE, 
    ADDEDBY, ADD_COMP_NAME, ADD_IPADD, ADD_OSUSER, UPD_COMP_NAME, 
    UPD_IPADD, UPD_OSUSER, UPDATEDDATE, UPDATEDBY, SCALE, 
    DATASOURCE, SALARY_1STEP_BEFORE)
 Values
   ('102202407/79', '102', 25, 'IPI-007001', 2020, 
    NULL, TO_DATE('06/Jul/24', 'DD/MON/YY'), 'Other Allowance', 'GRADE-12', NULL, 
    0, 0, 202407, '1', '025', 
    'IPI-006231', NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    'Form', NULL);
Insert into HR_EMPINCR_DET
   (REFNO, LTYPE, SLNO, EMPCODE, YEAROFSTRUC, 
    EDATE, TRNDATE, PARTICULAR, DESIGCODE, AMOUNTPRV, 
    AMOUNTCUR, SALPER, YEARMN, PRTCLR_TYPE, HEADCODE, 
    ADDEDBY, ADD_COMP_NAME, ADD_IPADD, ADD_OSUSER, UPD_COMP_NAME, 
    UPD_IPADD, UPD_OSUSER, UPDATEDDATE, UPDATEDBY, SCALE, 
    DATASOURCE, SALARY_1STEP_BEFORE)
 Values
   ('102202407/79', '102', 34, 'IPI-007001', 2020, 
    NULL, TO_DATE('06/Jul/24', 'DD/MON/YY'), 'City Allowance', 'GRADE-12', NULL, 
    0, 0, 202407, '1', '034', 
    'IPI-006231', NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    'Form', NULL);
Insert into HR_EMPINCR_DET
   (REFNO, LTYPE, SLNO, EMPCODE, YEAROFSTRUC, 
    EDATE, TRNDATE, PARTICULAR, DESIGCODE, AMOUNTPRV, 
    AMOUNTCUR, SALPER, YEARMN, PRTCLR_TYPE, HEADCODE, 
    ADDEDBY, ADD_COMP_NAME, ADD_IPADD, ADD_OSUSER, UPD_COMP_NAME, 
    UPD_IPADD, UPD_OSUSER, UPDATEDDATE, UPDATEDBY, SCALE, 
    DATASOURCE, SALARY_1STEP_BEFORE)
 Values
   ('102202407/79', '102', 37, 'IPI-007001', 2020, 
    NULL, TO_DATE('06/Jul/24', 'DD/MON/YY'), 'Allowance', 'GRADE-12', 2800, 
    2800, 3000, 202407, '1', '037', 
    'IPI-006231', NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    'Form', NULL);
COMMIT;
