CREATE TABLE HR_OVERTIME_DET_log
AS
    SELECT * FROM HR_OVERTIME_DET;
/

ALTER TABLE HR_OVERTIME_DET_log
    ADD sid NUMBER;
/

ALTER TABLE HR_OVERTIME_DET_log
    ADD serial# NUMBER;
/

ALTER TABLE HR_OVERTIME_DET_log
    ADD action_date DATE;
/

ALTER TABLE HR_OVERTIME_DET_log
    ADD action_status VARCHAR2 (5);
/

CREATE OR REPLACE TRIGGER TRI_HR_OVERTIME_DET_LOG
    AFTER DELETE OR INSERT OR UPDATE
    ON HR_OVERTIME_DET
    REFERENCING NEW AS new OLD AS old
    FOR EACH ROW
DECLARE
    v_sid      NUMBER;
    v_serial   NUMBER;
BEGIN
    SELECT sid, serial#
      INTO v_sid, v_serial
      FROM v$session
     WHERE audsid = USERENV ('SESSIONID');

    IF INSERTING
    THEN
        INSERT INTO HR_OVERTIME_DET_log (REFNO,
                                         REFDATE,
                                         EDATE,
                                         EMPCODE,
                                         EMPCODEOLD,
                                         SALARYGRADE,
                                         EMPLEVEL,
                                         BASIC,
                                         OTRATE,
                                         OTAMOUNT,
                                         ALLOWANCE,
                                         ARREAR,
                                         OTHERAMOUNT,
                                         USERNAME,
                                         UPDATEBY,
                                         UPDATEDATE,
                                         OTHOUR,
                                         YEARMN,
                                         YEARNO,
                                         MONTHNO,
                                         TRNTYPE,
                                         BUSINESSUNITID,
                                         BUSINESSUNIT,
                                         DESIG_CODE,
                                         DEIS_NAME,
                                         DEPT_CODE,
                                         DEPT_NAME,
                                         LOCID,
                                         LOCNAME,
                                         PAYTYPE,
                                         BANKACCOUNTNO,
                                         BANKNAME,
                                         COSTCENTER_ID,
                                         COSTCENTER_NAME,
                                         BANK_ID,
                                         BRANCH_NAME,
                                         DESIG_NAME,
                                         MISC,
                                         TRNFROM,
                                         SUBMODULE,
                                         sid,
                                         serial#,
                                         action_date,
                                         action_status)
             VALUES (:NEW.REFNO,
                     :NEW.REFDATE,
                     :NEW.EDATE,
                     :NEW.EMPCODE,
                     :NEW.EMPCODEOLD,
                     :NEW.SALARYGRADE,
                     :NEW.EMPLEVEL,
                     :NEW.BASIC,
                     :NEW.OTRATE,
                     :NEW.OTAMOUNT,
                     :NEW.ALLOWANCE,
                     :NEW.ARREAR,
                     :NEW.OTHERAMOUNT,
                     :NEW.USERNAME,
                     :NEW.UPDATEBY,
                     :NEW.UPDATEDATE,
                     :NEW.OTHOUR,
                     :NEW.YEARMN,
                     :NEW.YEARNO,
                     :NEW.MONTHNO,
                     :NEW.TRNTYPE,
                     :NEW.BUSINESSUNITID,
                     :NEW.BUSINESSUNIT,
                     :NEW.DESIG_CODE,
                     :NEW.DEIS_NAME,
                     :NEW.DEPT_CODE,
                     :NEW.DEPT_NAME,
                     :NEW.LOCID,
                     :NEW.LOCNAME,
                     :NEW.PAYTYPE,
                     :NEW.BANKACCOUNTNO,
                     :NEW.BANKNAME,
                     :NEW.COSTCENTER_ID,
                     :NEW.COSTCENTER_NAME,
                     :NEW.BANK_ID,
                     :NEW.BRANCH_NAME,
                     :NEW.DESIG_NAME,
                     :NEW.MISC,
                     :NEW.TRNFROM,
                     :NEW.SUBMODULE,
                     v_sid,
                     v_serial,
                     SYSDATE,
                     'I');
    ELSIF UPDATING
    THEN
        INSERT INTO HR_OVERTIME_DET_log (REFNO,
                                         REFDATE,
                                         EDATE,
                                         EMPCODE,
                                         EMPCODEOLD,
                                         SALARYGRADE,
                                         EMPLEVEL,
                                         BASIC,
                                         OTRATE,
                                         OTAMOUNT,
                                         ALLOWANCE,
                                         ARREAR,
                                         OTHERAMOUNT,
                                         USERNAME,
                                         UPDATEBY,
                                         UPDATEDATE,
                                         OTHOUR,
                                         YEARMN,
                                         YEARNO,
                                         MONTHNO,
                                         TRNTYPE,
                                         BUSINESSUNITID,
                                         BUSINESSUNIT,
                                         DESIG_CODE,
                                         DEIS_NAME,
                                         DEPT_CODE,
                                         DEPT_NAME,
                                         LOCID,
                                         LOCNAME,
                                         PAYTYPE,
                                         BANKACCOUNTNO,
                                         BANKNAME,
                                         COSTCENTER_ID,
                                         COSTCENTER_NAME,
                                         BANK_ID,
                                         BRANCH_NAME,
                                         DESIG_NAME,
                                         MISC,
                                         TRNFROM,
                                         SUBMODULE,
                                         sid,
                                         serial#,
                                         action_date,
                                         action_status)
             VALUES (:OLD.REFNO,
                     :OLD.REFDATE,
                     :OLD.EDATE,
                     :OLD.EMPCODE,
                     :OLD.EMPCODEOLD,
                     :OLD.SALARYGRADE,
                     :OLD.EMPLEVEL,
                     :OLD.BASIC,
                     :OLD.OTRATE,
                     :OLD.OTAMOUNT,
                     :OLD.ALLOWANCE,
                     :OLD.ARREAR,
                     :OLD.OTHERAMOUNT,
                     :OLD.USERNAME,
                     :OLD.UPDATEBY,
                     :OLD.UPDATEDATE,
                     :OLD.OTHOUR,
                     :OLD.YEARMN,
                     :OLD.YEARNO,
                     :OLD.MONTHNO,
                     :OLD.TRNTYPE,
                     :OLD.BUSINESSUNITID,
                     :OLD.BUSINESSUNIT,
                     :OLD.DESIG_CODE,
                     :OLD.DEIS_NAME,
                     :OLD.DEPT_CODE,
                     :OLD.DEPT_NAME,
                     :OLD.LOCID,
                     :OLD.LOCNAME,
                     :OLD.PAYTYPE,
                     :OLD.BANKACCOUNTNO,
                     :OLD.BANKNAME,
                     :OLD.COSTCENTER_ID,
                     :OLD.COSTCENTER_NAME,
                     :OLD.BANK_ID,
                     :OLD.BRANCH_NAME,
                     :OLD.DESIG_NAME,
                     :OLD.MISC,
                     :OLD.TRNFROM,
                     :OLD.SUBMODULE,
                     v_sid,
                     v_serial,
                     SYSDATE,
                     'U');
    ELSIF DELETING
    THEN
        INSERT INTO HR_OVERTIME_DET_log (REFNO,
                                         REFDATE,
                                         EDATE,
                                         EMPCODE,
                                         EMPCODEOLD,
                                         SALARYGRADE,
                                         EMPLEVEL,
                                         BASIC,
                                         OTRATE,
                                         OTAMOUNT,
                                         ALLOWANCE,
                                         ARREAR,
                                         OTHERAMOUNT,
                                         USERNAME,
                                         UPDATEBY,
                                         UPDATEDATE,
                                         OTHOUR,
                                         YEARMN,
                                         YEARNO,
                                         MONTHNO,
                                         TRNTYPE,
                                         BUSINESSUNITID,
                                         BUSINESSUNIT,
                                         DESIG_CODE,
                                         DEIS_NAME,
                                         DEPT_CODE,
                                         DEPT_NAME,
                                         LOCID,
                                         LOCNAME,
                                         PAYTYPE,
                                         BANKACCOUNTNO,
                                         BANKNAME,
                                         COSTCENTER_ID,
                                         COSTCENTER_NAME,
                                         BANK_ID,
                                         BRANCH_NAME,
                                         DESIG_NAME,
                                         MISC,
                                         TRNFROM,
                                         SUBMODULE,
                                         sid,
                                         serial#,
                                         action_date,
                                         action_status)
             VALUES (:OLD.REFNO,
                     :OLD.REFDATE,
                     :OLD.EDATE,
                     :OLD.EMPCODE,
                     :OLD.EMPCODEOLD,
                     :OLD.SALARYGRADE,
                     :OLD.EMPLEVEL,
                     :OLD.BASIC,
                     :OLD.OTRATE,
                     :OLD.OTAMOUNT,
                     :OLD.ALLOWANCE,
                     :OLD.ARREAR,
                     :OLD.OTHERAMOUNT,
                     :OLD.USERNAME,
                     :OLD.UPDATEBY,
                     :OLD.UPDATEDATE,
                     :OLD.OTHOUR,
                     :OLD.YEARMN,
                     :OLD.YEARNO,
                     :OLD.MONTHNO,
                     :OLD.TRNTYPE,
                     :OLD.BUSINESSUNITID,
                     :OLD.BUSINESSUNIT,
                     :OLD.DESIG_CODE,
                     :OLD.DEIS_NAME,
                     :OLD.DEPT_CODE,
                     :OLD.DEPT_NAME,
                     :OLD.LOCID,
                     :OLD.LOCNAME,
                     :OLD.PAYTYPE,
                     :OLD.BANKACCOUNTNO,
                     :OLD.BANKNAME,
                     :OLD.COSTCENTER_ID,
                     :OLD.COSTCENTER_NAME,
                     :OLD.BANK_ID,
                     :OLD.BRANCH_NAME,
                     :OLD.DESIG_NAME,
                     :OLD.MISC,
                     :OLD.TRNFROM,
                     :OLD.SUBMODULE,
                     v_sid,
                     v_serial,
                     SYSDATE,
                     'D');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS
    THEN
        NULL;
END;
/