/* Formatted on 4/27/2025 12:55:01 PM (QP5 v5.362) */
CREATE TABLE t_structure
AS
    SELECT * FROM hr_empsalstructure;


MERGE INTO hr_empsalstructure TRGT
     USING (SELECT SLNO,
                   EMPCODE,
                   YEAROFSTRUC,
                   EDATE,
                   TRNDATE,
                   PARTICULAR,
                   DESIGCODE,
                   AMOUNTPRV,
                   AMOUNTCUR,
                   SALPER,
                   REFNO,
                   YEARMN,
                   PRTCLR_TYPE,
                   PTC_FLAT,
                   HEADCODE,
                   SL,
                   ADDEDBY,
                   ADD_COMP_NAME,
                   ADD_IPADD,
                   ADD_OSUSER,
                   UPD_COMP_NAME,
                   UPD_IPADD,
                   UPD_OSUSER,
                   UPDATEDDATE,
                   UPDATEDBY,
                   SCALE,
                   AMT_B4_F,
                   AMT_AFTER_F,
                   AMT_2B4_F
              FROM t_structure) SRC
        ON (TRGT.SLNO = SRC.SLNO AND TRGT.EMPCODE = SRC.EMPCODE)
WHEN MATCHED
THEN
    UPDATE SET TRGT.YEAROFSTRUC = SRC.YEAROFSTRUC,
               TRGT.EDATE = SRC.EDATE,
               TRGT.TRNDATE = SRC.TRNDATE,
               TRGT.PARTICULAR = SRC.PARTICULAR,
               TRGT.DESIGCODE = SRC.DESIGCODE,
               TRGT.AMOUNTCUR = SRC.AMOUNTCUR,
               TRGT.SALPER = SRC.SALPER,
               TRGT.REFNO = SRC.REFNO,
               TRGT.YEARMN = SRC.YEARMN,
               TRGT.PRTCLR_TYPE = SRC.PRTCLR_TYPE,
               TRGT.PTC_FLAT = SRC.PTC_FLAT,
               TRGT.HEADCODE = SRC.HEADCODE,
               TRGT.SL = SRC.SL,
               TRGT.ADDEDBY = SRC.ADDEDBY,
               TRGT.ADD_COMP_NAME = SRC.ADD_COMP_NAME,
               TRGT.ADD_IPADD = SRC.ADD_IPADD,
               TRGT.ADD_OSUSER = SRC.ADD_OSUSER,
               TRGT.UPD_COMP_NAME = SRC.UPD_COMP_NAME,
               TRGT.UPD_IPADD = SRC.UPD_IPADD,
               TRGT.UPD_OSUSER = SRC.UPD_OSUSER,
               TRGT.UPDATEDDATE = SRC.UPDATEDDATE,
               TRGT.UPDATEDBY = SRC.UPDATEDBY,
               TRGT.SCALE = SRC.SCALE,
               TRGT.AMT_B4_F = SRC.AMT_B4_F,
               TRGT.AMT_AFTER_F = SRC.AMT_AFTER_F,
               TRGT.AMT_2B4_F = SRC.AMT_2B4_F
WHEN NOT MATCHED
THEN
    INSERT     (SLNO,
                EMPCODE,
                YEAROFSTRUC,
                EDATE,
                TRNDATE,
                PARTICULAR,
                DESIGCODE,
                AMOUNTCUR,
                SALPER,
                REFNO,
                YEARMN,
                PRTCLR_TYPE,
                PTC_FLAT,
                HEADCODE,
                SL,
                ADDEDBY,
                ADD_COMP_NAME,
                ADD_IPADD,
                ADD_OSUSER,
                UPD_COMP_NAME,
                UPD_IPADD,
                UPD_OSUSER,
                UPDATEDDATE,
                UPDATEDBY,
                SCALE,
                AMT_B4_F,
                AMT_AFTER_F,
                AMT_2B4_F)
        VALUES (SRC.SLNO,
                SRC.EMPCODE,
                SRC.YEAROFSTRUC,
                SRC.EDATE,
                SRC.TRNDATE,
                SRC.PARTICULAR,
                SRC.DESIGCODE,
                SRC.AMOUNTCUR,
                SRC.SALPER,
                SRC.REFNO,
                SRC.YEARMN,
                SRC.PRTCLR_TYPE,
                SRC.PTC_FLAT,
                SRC.HEADCODE,
                SRC.SL,
                SRC.ADDEDBY,
                SRC.ADD_COMP_NAME,
                SRC.ADD_IPADD,
                SRC.ADD_OSUSER,
                SRC.UPD_COMP_NAME,
                SRC.UPD_IPADD,
                SRC.UPD_OSUSER,
                SRC.UPDATEDDATE,
                SRC.UPDATEDBY,
                SRC.SCALE,
                SRC.AMT_B4_F,
                SRC.AMT_AFTER_F,
                SRC.AMT_2B4_F);