-- 1. Table to store current salary components
CREATE TABLE pr_salary_components (
    emp_id          NUMBER PRIMARY KEY,
    basic_salary    NUMBER(12,2),
    house_rent      NUMBER(12,2),
    medical_allow   NUMBER(12,2),
    conveyance      NUMBER(12,2),
    FOOD_ALW  NUMBER(12,2),
    last_updated    DATE,
    CONSTRAINT fk_sal_emp FOREIGN KEY (emp_id) REFERENCES pr_employee_list(emp_id)
);

-- 2. Table to store the audit trail (History)
CREATE TABLE pr_increment_history (
    hist_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id          NUMBER,
    old_gross       NUMBER(12,2),
    new_gross       NUMBER(12,2),
    old_basic       NUMBER(12,2),
    new_basic       NUMBER(12,2),
    increment_date  DATE,
    remarks         VARCHAR2(200),
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

BEGIN
   sp_apply_yearly_increment (DATE '2026-01-26', DATE '2026-02-25');
END;