/*
  School Management ERP - Oracle SQL Converted Schema
  Converted from: allscript.sql (PostgreSQL)
  Target: Oracle Database 12c/19c/21c/23ai compatible style

  Recommended run order:
  1) Create/connect to an Oracle schema user, for example SMS.
     -- Run once as SYS/SYSTEM/DBA if needed:
     -- CREATE USER sms IDENTIFIED BY YourStrongPassword
     --   DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp QUOTA UNLIMITED ON users;
     -- GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE,
     --       CREATE TRIGGER, CREATE PROCEDURE, CREATE INDEXTYPE TO sms;

  2) Connect as SMS and run this script.
     This script does not use the sms. prefix because Oracle schema = connected user.

  Important conversion notes:
  - BIGSERIAL      -> NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY
  - BIGINT         -> NUMBER(19)
  - BOOLEAN        -> NUMBER(1), where 1 = TRUE and 0 = FALSE
  - TIMESTAMPTZ    -> TIMESTAMP WITH TIME ZONE
  - TEXT/JSONB     -> CLOB; JSON columns include IS JSON checks
  - UUID           -> VARCHAR2(36) DEFAULT LOWER(RAWTOHEX(SYS_GUID()))
  - INET           -> VARCHAR2(45)
  - PostgreSQL TIME-> VARCHAR2(8), store as HH24:MI:SS
  - PostgreSQL trigger function replaced by individual Oracle row triggers
  - PostgreSQL GIN full-text index converted to a normal b-tree index
*/

/* ============================================================
   0. COMMON NOTES
   ============================================================ */
-- PostgreSQL fn_set_updated_at() removed. Oracle row-level triggers are generated at the end of this script.

/* ============================================================
   1. CORE ORGANIZATION / MULTI-BRANCH
   ============================================================ */

CREATE TABLE institutions (
  institution_id      NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  institution_code    VARCHAR2(30) UNIQUE NOT NULL,
  institution_name    VARCHAR2(200) NOT NULL,
  institution_type    VARCHAR2(50) NOT NULL, -- School, College, Madrasa, Coaching, etc.
  eiin_no             VARCHAR2(50),
  registration_no     VARCHAR2(80),
  phone               VARCHAR2(30),
  email               VARCHAR2(150),
  website             VARCHAR2(150),
  logo_url            CLOB,
  address_line        CLOB,
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT chk_institutions_status CHECK (status IN ('ACTIVE','INACTIVE'))
);

CREATE TABLE branches (
  branch_id           NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  institution_id      NUMBER(19) NOT NULL REFERENCES institutions(institution_id) ON DELETE CASCADE,
  branch_code         VARCHAR2(30) NOT NULL,
  branch_name         VARCHAR2(150) NOT NULL,
  branch_type         VARCHAR2(50), -- Main, Sub Branch, Campus
  phone               VARCHAR2(30),
  email               VARCHAR2(150),
  address_line        CLOB,
  is_main_branch      NUMBER(1) DEFAULT 0 NOT NULL CHECK (is_main_branch IN (0,1)),
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uk_branches_code UNIQUE (institution_id, branch_code),
  CONSTRAINT chk_branches_status CHECK (status IN ('ACTIVE','INACTIVE'))
);

CREATE TABLE academic_years (
  academic_year_id    NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  institution_id      NUMBER(19) NOT NULL REFERENCES institutions(institution_id) ON DELETE CASCADE,
  year_name           VARCHAR2(30) NOT NULL, -- 2026
  start_date          DATE NOT NULL,
  end_date            DATE NOT NULL,
  is_current          NUMBER(1) DEFAULT 0 NOT NULL CHECK (is_current IN (0,1)),
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uk_academic_years UNIQUE (institution_id, year_name),
  CONSTRAINT chk_academic_year_dates CHECK (end_date >= start_date)
);

CREATE TABLE academic_sessions (
  session_id          NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  institution_id      NUMBER(19) NOT NULL REFERENCES institutions(institution_id) ON DELETE CASCADE,
  academic_year_id    NUMBER(19) REFERENCES academic_years(academic_year_id),
  session_name        VARCHAR2(80) NOT NULL, -- 2026, 2025-26, Spring, Board Exam Year etc.
  session_type        VARCHAR2(50) DEFAULT 'ACADEMIC',
  start_date          DATE,
  end_date            DATE,
  is_current          NUMBER(1) DEFAULT 0 NOT NULL CHECK (is_current IN (0,1)),
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uk_academic_sessions UNIQUE (institution_id, session_name, session_type)
);

CREATE TABLE lookup_types (
  lookup_type_id      NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  type_code           VARCHAR2(50) UNIQUE NOT NULL,
  type_name           VARCHAR2(100) NOT NULL,
  description         CLOB,
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL
);

CREATE TABLE lookup_values (
  lookup_value_id     NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  lookup_type_id      NUMBER(19) NOT NULL REFERENCES lookup_types(lookup_type_id) ON DELETE CASCADE,
  value_code          VARCHAR2(50) NOT NULL,
  value_name          VARCHAR2(150) NOT NULL,
  sort_order          NUMBER(10) DEFAULT 0,
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  CONSTRAINT uk_lookup_values UNIQUE (lookup_type_id, value_code)
);

/* ============================================================
   2. AUTHENTICATION, USER, ROLE, MENU PERMISSION
   ============================================================ */

CREATE TABLE appuser (
  id             NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  institution_id      NUMBER(19) REFERENCES institutions(institution_id) ON DELETE CASCADE,
  branch_id           NUMBER(19) REFERENCES branches(branch_id) ON DELETE SET NULL,
  username            VARCHAR2(80) UNIQUE NOT NULL,
  email               VARCHAR2(150) UNIQUE,
  mobile              VARCHAR2(30),
  password_hash       CLOB NOT NULL,
  full_name           VARCHAR2(150) NOT NULL,
  user_type           VARCHAR2(30) DEFAULT 'STAFF' NOT NULL, -- ADMIN, TEACHER, STAFF, STUDENT, GUARDIAN
  avatar_url          CLOB,
  is_super_admin      NUMBER(1) DEFAULT 0 NOT NULL CHECK (is_super_admin IN (0,1)),
  is_active           NUMBER(1) DEFAULT 1 NOT NULL CHECK (is_active IN (0,1)),
  last_login_at       TIMESTAMP WITH TIME ZONE,
  password_changed_at TIMESTAMP WITH TIME ZONE,
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT chk_appuser_type CHECK (user_type IN ('SUPER_ADMIN','ADMIN','TEACHER','STAFF','STUDENT','GUARDIAN'))
);

CREATE TABLE roles (
  role_id             NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  institution_id      NUMBER(19) REFERENCES institutions(institution_id) ON DELETE CASCADE,
  role_code           VARCHAR2(50) NOT NULL,
  role_name           VARCHAR2(100) NOT NULL,
  description         CLOB,
  is_system_role      NUMBER(1) DEFAULT 0 NOT NULL CHECK (is_system_role IN (0,1)),
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uk_roles UNIQUE (institution_id, role_code)
);

CREATE TABLE permissions (
  permission_id       NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  permission_code     VARCHAR2(100) UNIQUE NOT NULL, -- student.create, fee.collect
  permission_name     VARCHAR2(150) NOT NULL,
  module_name         VARCHAR2(80) NOT NULL,
  description         CLOB,
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL
);

CREATE TABLE role_permissions (
  role_id             NUMBER(19) NOT NULL REFERENCES roles(role_id) ON DELETE CASCADE,
  permission_id       NUMBER(19) NOT NULL REFERENCES permissions(permission_id) ON DELETE CASCADE,
  can_view            NUMBER(1) DEFAULT 1 NOT NULL CHECK (can_view IN (0,1)),
  can_create          NUMBER(1) DEFAULT 0 NOT NULL CHECK (can_create IN (0,1)),
  can_update          NUMBER(1) DEFAULT 0 NOT NULL CHECK (can_update IN (0,1)),
  can_delete          NUMBER(1) DEFAULT 0 NOT NULL CHECK (can_delete IN (0,1)),
  can_approve         NUMBER(1) DEFAULT 0 NOT NULL CHECK (can_approve IN (0,1)),
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE user_roles (
  id             NUMBER(19) NOT NULL REFERENCES appuser(id) ON DELETE CASCADE,
  role_id             NUMBER(19) NOT NULL REFERENCES roles(role_id) ON DELETE CASCADE,
  branch_id           NUMBER(19) REFERENCES branches(branch_id) ON DELETE CASCADE,
  assigned_at         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  PRIMARY KEY (id, role_id, branch_id)
);

CREATE TABLE menus (
  menu_id             NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  parent_menu_id      NUMBER(19) REFERENCES menus(menu_id) ON DELETE SET NULL,
  menu_code           VARCHAR2(80) UNIQUE NOT NULL,
  menu_title          VARCHAR2(120) NOT NULL,
  route_path          VARCHAR2(200),
  icon_name           VARCHAR2(80),
  sort_order          NUMBER(10) DEFAULT 0 NOT NULL,
  is_visible          NUMBER(1) DEFAULT 1 NOT NULL CHECK (is_visible IN (0,1)),
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL
);

CREATE TABLE role_menus (
  role_id             NUMBER(19) NOT NULL REFERENCES roles(role_id) ON DELETE CASCADE,
  menu_id             NUMBER(19) NOT NULL REFERENCES menus(menu_id) ON DELETE CASCADE,
  can_access          NUMBER(1) DEFAULT 1 NOT NULL CHECK (can_access IN (0,1)),
  PRIMARY KEY (role_id, menu_id)
);

CREATE TABLE user_sessions (
  session_id          VARCHAR2(36) DEFAULT LOWER(RAWTOHEX(SYS_GUID())) PRIMARY KEY,
  id             NUMBER(19) NOT NULL REFERENCES appuser(id) ON DELETE CASCADE,
  refresh_token_hash  CLOB,
  ip_address          VARCHAR2(45),
  user_agent          CLOB,
  expires_at          TIMESTAMP WITH TIME ZONE NOT NULL,
  revoked_at          TIMESTAMP WITH TIME ZONE,
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE password_reset_tokens (
  token_id            NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  id             NUMBER(19) NOT NULL REFERENCES appuser(id) ON DELETE CASCADE,
  token_hash          CLOB NOT NULL,
  expires_at          TIMESTAMP WITH TIME ZONE NOT NULL,
  used_at             TIMESTAMP WITH TIME ZONE,
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE login_audit (
  login_audit_id      NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  id             NUMBER(19) REFERENCES appuser(id) ON DELETE SET NULL,
  username            VARCHAR2(100),
  login_status        VARCHAR2(20) NOT NULL, -- SUCCESS, FAILED
  failure_reason      CLOB,
  ip_address          VARCHAR2(45),
  user_agent          CLOB,
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

/* ============================================================
   3. ACADEMIC MASTER SETUP
   ============================================================ */

CREATE TABLE education_boards (
  board_id            NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  board_code          VARCHAR2(30) UNIQUE NOT NULL,
  board_name          VARCHAR2(120) NOT NULL,
  country_name        VARCHAR2(80) DEFAULT 'Bangladesh',
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL
);

CREATE TABLE mediums (
  medium_id           NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  institution_id      NUMBER(19) REFERENCES institutions(institution_id) ON DELETE CASCADE,
  medium_name         VARCHAR2(80) NOT NULL, -- Bangla, English Version, English Medium
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  CONSTRAINT uk_mediums UNIQUE (institution_id, medium_name)
);

CREATE TABLE shifts (
  shift_id            NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  institution_id      NUMBER(19) NOT NULL REFERENCES institutions(institution_id) ON DELETE CASCADE,
  shift_name          VARCHAR2(80) NOT NULL, -- Morning, Day, Evening
  start_time          VARCHAR2(8),
  end_time            VARCHAR2(8),
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  CONSTRAINT uk_shifts UNIQUE (institution_id, shift_name)
);

CREATE TABLE class_levels (
  class_id            NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  institution_id      NUMBER(19) NOT NULL REFERENCES institutions(institution_id) ON DELETE CASCADE,
  class_code          VARCHAR2(30) NOT NULL,
  class_name          VARCHAR2(100) NOT NULL, -- Play, One, Ten, HSC 1st Year
  numeric_level       NUMBER(10),
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uk_class_levels UNIQUE (institution_id, class_code)
);

CREATE TABLE groups (
  group_id            NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  institution_id      NUMBER(19) NOT NULL REFERENCES institutions(institution_id) ON DELETE CASCADE,
  group_name          VARCHAR2(100) NOT NULL, -- Science, Business Studies, Humanities, General
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  CONSTRAINT uk_groups UNIQUE (institution_id, group_name)
);

CREATE TABLE sections (
  section_id          NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  institution_id      NUMBER(19) NOT NULL REFERENCES institutions(institution_id) ON DELETE CASCADE,
  section_name        VARCHAR2(50) NOT NULL, -- A, B, C
  capacity            NUMBER(10),
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  CONSTRAINT uk_sections UNIQUE (institution_id, section_name)
);

CREATE TABLE classrooms (
  classroom_id        NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  branch_id           NUMBER(19) NOT NULL REFERENCES branches(branch_id) ON DELETE CASCADE,
  room_no             VARCHAR2(50) NOT NULL,
  building_name       VARCHAR2(100),
  floor_no            VARCHAR2(30),
  capacity            NUMBER(10),
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  CONSTRAINT uk_classrooms UNIQUE (branch_id, room_no)
);

CREATE TABLE subjects (
  subject_id          NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  institution_id      NUMBER(19) NOT NULL REFERENCES institutions(institution_id) ON DELETE CASCADE,
  subject_code        VARCHAR2(30) NOT NULL,
  subject_name        VARCHAR2(150) NOT NULL,
  subject_type        VARCHAR2(30) DEFAULT 'REGULAR', -- REGULAR, OPTIONAL, FOURTH_SUBJECT
  full_marks          NUMBER(8,2) DEFAULT 100,
  pass_marks          NUMBER(8,2) DEFAULT 33,
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  CONSTRAINT uk_subjects UNIQUE (institution_id, subject_code)
);

CREATE TABLE class_subjects (
  class_subject_id    NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  institution_id      NUMBER(19) NOT NULL REFERENCES institutions(institution_id) ON DELETE CASCADE,
  class_id            NUMBER(19) NOT NULL REFERENCES class_levels(class_id) ON DELETE CASCADE,
  group_id            NUMBER(19) REFERENCES groups(group_id) ON DELETE SET NULL,
  subject_id          NUMBER(19) NOT NULL REFERENCES subjects(subject_id) ON DELETE CASCADE,
  is_mandatory        NUMBER(1) DEFAULT 1 NOT NULL CHECK (is_mandatory IN (0,1)),
  sort_order          NUMBER(10) DEFAULT 0,
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  CONSTRAINT uk_class_subjects UNIQUE (class_id, group_id, subject_id)
);

CREATE TABLE academic_batches (
  batch_id            NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  branch_id           NUMBER(19) NOT NULL REFERENCES branches(branch_id) ON DELETE CASCADE,
  academic_year_id    NUMBER(19) NOT NULL REFERENCES academic_years(academic_year_id) ON DELETE CASCADE,
  class_id            NUMBER(19) NOT NULL REFERENCES class_levels(class_id),
  group_id            NUMBER(19) REFERENCES groups(group_id),
  section_id          NUMBER(19) REFERENCES sections(section_id),
  medium_id           NUMBER(19) REFERENCES mediums(medium_id),
  shift_id            NUMBER(19) REFERENCES shifts(shift_id),
  classroom_id        NUMBER(19) REFERENCES classrooms(classroom_id),
  batch_name          VARCHAR2(150) NOT NULL,
  capacity            NUMBER(10),
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uk_academic_batches UNIQUE (branch_id, academic_year_id, class_id, group_id, section_id, medium_id, shift_id)
);

/* ============================================================
   4. STUDENT ADMISSION / PROFILE / GUARDIAN
   ============================================================ */

CREATE TABLE students (
  student_id          NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  institution_id      NUMBER(19) NOT NULL REFERENCES institutions(institution_id) ON DELETE CASCADE,
  id             NUMBER(19) UNIQUE REFERENCES appuser(id) ON DELETE SET NULL,
  student_no          VARCHAR2(50) NOT NULL,
  admission_no        VARCHAR2(50),
  registration_no     VARCHAR2(80),
  first_name          VARCHAR2(100) NOT NULL,
  last_name           VARCHAR2(100),
  full_name           VARCHAR2(180) GENERATED ALWAYS AS (trim(coalesce(first_name,'') || ' ' || coalesce(last_name,''))) VIRTUAL,
  gender              VARCHAR2(20),
  date_of_birth       DATE,
  birth_certificate_no VARCHAR2(80),
  nid_no              VARCHAR2(80),
  blood_group         VARCHAR2(10),
  religion            VARCHAR2(50),
  nationality         VARCHAR2(80) DEFAULT 'Bangladeshi',
  photo_url           CLOB,
  mobile              VARCHAR2(30),
  email               VARCHAR2(150),
  status              VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL, -- ACTIVE, INACTIVE, TC, GRADUATED, DROPOUT
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uk_students_no UNIQUE (institution_id, student_no),
  CONSTRAINT chk_students_gender CHECK (gender IS NULL OR gender IN ('MALE','FEMALE','OTHER'))
);

CREATE TABLE student_admissions (
  admission_id        NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  student_id          NUMBER(19) NOT NULL REFERENCES students(student_id) ON DELETE CASCADE,
  branch_id           NUMBER(19) NOT NULL REFERENCES branches(branch_id),
  academic_year_id    NUMBER(19) NOT NULL REFERENCES academic_years(academic_year_id),
  admission_date      DATE DEFAULT CURRENT_DATE NOT NULL,
  admission_type      VARCHAR2(30) DEFAULT 'NEW', -- NEW, TRANSFER, RE_ADMISSION
  previous_institute  VARCHAR2(200),
  previous_class      VARCHAR2(100),
  approved_by         NUMBER(19) REFERENCES appuser(id),
  approval_status     VARCHAR2(30) DEFAULT 'PENDING' NOT NULL, -- PENDING, APPROVED, REJECTED
  remarks             CLOB,
  created_by          NUMBER(19) REFERENCES appuser(id),
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE guardians (
  guardian_id         NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  institution_id      NUMBER(19) NOT NULL REFERENCES institutions(institution_id) ON DELETE CASCADE,
  id             NUMBER(19) UNIQUE REFERENCES appuser(id) ON DELETE SET NULL,
  guardian_name       VARCHAR2(150) NOT NULL,
  relation_name       VARCHAR2(50), -- Father, Mother, Uncle etc.
  occupation          VARCHAR2(100),
  nid_no              VARCHAR2(80),
  mobile              VARCHAR2(30),
  alternate_mobile    VARCHAR2(30),
  email               VARCHAR2(150),
  monthly_income      NUMBER(12,2),
  address_line        CLOB,
  photo_url           CLOB,
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE student_guardians (
  student_guardian_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  student_id          NUMBER(19) NOT NULL REFERENCES students(student_id) ON DELETE CASCADE,
  guardian_id         NUMBER(19) NOT NULL REFERENCES guardians(guardian_id) ON DELETE CASCADE,
  relation_type       VARCHAR2(50) NOT NULL, -- FATHER, MOTHER, LOCAL_GUARDIAN
  is_primary          NUMBER(1) DEFAULT 0 NOT NULL CHECK (is_primary IN (0,1)),
  is_emergency_contact NUMBER(1) DEFAULT 0 NOT NULL CHECK (is_emergency_contact IN (0,1)),
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uk_student_guardians UNIQUE (student_id, guardian_id, relation_type)
);

CREATE TABLE student_addresses (
  address_id          NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  student_id          NUMBER(19) NOT NULL REFERENCES students(student_id) ON DELETE CASCADE,
  address_type        VARCHAR2(30) NOT NULL, -- PRESENT, PERMANENT
  village_road        VARCHAR2(200),
  post_office         VARCHAR2(120),
  thana_upazila       VARCHAR2(120),
  district            VARCHAR2(120),
  division            VARCHAR2(120),
  postal_code         VARCHAR2(20),
  country             VARCHAR2(80) DEFAULT 'Bangladesh',
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uk_student_addresses UNIQUE (student_id, address_type)
);

CREATE TABLE student_enrollments (
  enrollment_id       NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  student_id          NUMBER(19) NOT NULL REFERENCES students(student_id) ON DELETE CASCADE,
  branch_id           NUMBER(19) NOT NULL REFERENCES branches(branch_id),
  academic_year_id    NUMBER(19) NOT NULL REFERENCES academic_years(academic_year_id),
  batch_id            NUMBER(19) NOT NULL REFERENCES academic_batches(batch_id),
  roll_no             VARCHAR2(30),
  class_id            NUMBER(19) NOT NULL REFERENCES class_levels(class_id),
  group_id            NUMBER(19) REFERENCES groups(group_id),
  section_id          NUMBER(19) REFERENCES sections(section_id),
  medium_id           NUMBER(19) REFERENCES mediums(medium_id),
  shift_id            NUMBER(19) REFERENCES shifts(shift_id),
  enrollment_status   VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL, -- ACTIVE, PROMOTED, TRANSFERRED, DROPPED
  start_date          DATE DEFAULT CURRENT_DATE NOT NULL,
  end_date            DATE,
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uk_student_year UNIQUE (student_id, academic_year_id),
  CONSTRAINT uk_batch_roll UNIQUE (batch_id, roll_no)
);

CREATE TABLE student_documents (
  document_id         NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  student_id          NUMBER(19) NOT NULL REFERENCES students(student_id) ON DELETE CASCADE,
  document_type       VARCHAR2(80) NOT NULL, -- Birth Certificate, Photo, TC, Marksheet
  document_title      VARCHAR2(150),
  file_url            CLOB NOT NULL,
  uploaded_by         NUMBER(19) REFERENCES appuser(id),
  uploaded_at         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL
);

CREATE TABLE student_status_history (
  status_history_id   NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  student_id          NUMBER(19) NOT NULL REFERENCES students(student_id) ON DELETE CASCADE,
  old_status          VARCHAR2(30),
  new_status          VARCHAR2(30) NOT NULL,
  effective_date      DATE DEFAULT CURRENT_DATE NOT NULL,
  reason              CLOB,
  changed_by          NUMBER(19) REFERENCES appuser(id),
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE promotions (
  promotion_id        NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  institution_id      NUMBER(19) NOT NULL REFERENCES institutions(institution_id) ON DELETE CASCADE,
  from_academic_year_id NUMBER(19) NOT NULL REFERENCES academic_years(academic_year_id),
  to_academic_year_id NUMBER(19) NOT NULL REFERENCES academic_years(academic_year_id),
  promotion_date      DATE DEFAULT CURRENT_DATE NOT NULL,
  promotion_status    VARCHAR2(30) DEFAULT 'DRAFT' NOT NULL, -- DRAFT, APPROVED, CANCELLED
  remarks             CLOB,
  created_by          NUMBER(19) REFERENCES appuser(id),
  approved_by         NUMBER(19) REFERENCES appuser(id),
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE promotion_details (
  promotion_detail_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  promotion_id        NUMBER(19) NOT NULL REFERENCES promotions(promotion_id) ON DELETE CASCADE,
  student_id          NUMBER(19) NOT NULL REFERENCES students(student_id),
  from_enrollment_id  NUMBER(19) REFERENCES student_enrollments(enrollment_id),
  to_batch_id         NUMBER(19) REFERENCES academic_batches(batch_id),
  to_roll_no          VARCHAR2(30),
  result_status       VARCHAR2(30), -- PASSED, FAILED, PROMOTED
  remarks             CLOB,
  CONSTRAINT uk_promotion_student UNIQUE (promotion_id, student_id)
);

/* ============================================================
   5. HR / TEACHER / STAFF
   ============================================================ */

CREATE TABLE departments (
  department_id       NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  institution_id      NUMBER(19) NOT NULL REFERENCES institutions(institution_id) ON DELETE CASCADE,
  department_code     VARCHAR2(30) NOT NULL,
  department_name     VARCHAR2(120) NOT NULL,
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  CONSTRAINT uk_departments UNIQUE (institution_id, department_code)
);

CREATE TABLE designations (
  designation_id      NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  institution_id      NUMBER(19) NOT NULL REFERENCES institutions(institution_id) ON DELETE CASCADE,
  designation_code    VARCHAR2(30) NOT NULL,
  designation_name    VARCHAR2(120) NOT NULL,
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  CONSTRAINT uk_designations UNIQUE (institution_id, designation_code)
);

CREATE TABLE employees (
  employee_id         NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  institution_id      NUMBER(19) NOT NULL REFERENCES institutions(institution_id) ON DELETE CASCADE,
  branch_id           NUMBER(19) REFERENCES branches(branch_id),
  id             NUMBER(19) UNIQUE REFERENCES appuser(id) ON DELETE SET NULL,
  employee_no         VARCHAR2(50) NOT NULL,
  first_name          VARCHAR2(100) NOT NULL,
  last_name           VARCHAR2(100),
  full_name           VARCHAR2(180) GENERATED ALWAYS AS (trim(coalesce(first_name,'') || ' ' || coalesce(last_name,''))) VIRTUAL,
  employee_type       VARCHAR2(30) DEFAULT 'STAFF' NOT NULL, -- TEACHER, STAFF, ADMIN
  department_id       NUMBER(19) REFERENCES departments(department_id),
  designation_id      NUMBER(19) REFERENCES designations(designation_id),
  joining_date        DATE,
  date_of_birth       DATE,
  gender              VARCHAR2(20),
  blood_group         VARCHAR2(10),
  religion            VARCHAR2(50),
  nid_no              VARCHAR2(80),
  mobile              VARCHAR2(30),
  email               VARCHAR2(150),
  photo_url           CLOB,
  employment_status   VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL, -- ACTIVE, RESIGNED, TERMINATED
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uk_employees_no UNIQUE (institution_id, employee_no),
  CONSTRAINT chk_employees_type CHECK (employee_type IN ('TEACHER','STAFF','ADMIN'))
);

CREATE TABLE employee_addresses (
  address_id          NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  employee_id         NUMBER(19) NOT NULL REFERENCES employees(employee_id) ON DELETE CASCADE,
  address_type        VARCHAR2(30) NOT NULL, -- PRESENT, PERMANENT
  address_line        CLOB,
  district            VARCHAR2(120),
  division            VARCHAR2(120),
  postal_code         VARCHAR2(20),
  country             VARCHAR2(80) DEFAULT 'Bangladesh',
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uk_employee_addresses UNIQUE (employee_id, address_type)
);

CREATE TABLE teacher_subject_assignments (
  assignment_id       NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  employee_id         NUMBER(19) NOT NULL REFERENCES employees(employee_id) ON DELETE CASCADE,
  academic_year_id    NUMBER(19) NOT NULL REFERENCES academic_years(academic_year_id),
  batch_id            NUMBER(19) NOT NULL REFERENCES academic_batches(batch_id),
  subject_id          NUMBER(19) NOT NULL REFERENCES subjects(subject_id),
  is_class_teacher    NUMBER(1) DEFAULT 0 NOT NULL CHECK (is_class_teacher IN (0,1)),
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uk_teacher_subject UNIQUE (employee_id, academic_year_id, batch_id, subject_id)
);

CREATE TABLE leave_types (
  leave_type_id       NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  institution_id      NUMBER(19) NOT NULL REFERENCES institutions(institution_id) ON DELETE CASCADE,
  leave_code          VARCHAR2(30) NOT NULL,
  leave_name          VARCHAR2(100) NOT NULL,
  yearly_limit_days   NUMBER(6,2),
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  CONSTRAINT uk_leave_types UNIQUE (institution_id, leave_code)
);

CREATE TABLE employee_leave_applications (
  leave_application_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  employee_id         NUMBER(19) NOT NULL REFERENCES employees(employee_id) ON DELETE CASCADE,
  leave_type_id       NUMBER(19) NOT NULL REFERENCES leave_types(leave_type_id),
  from_date           DATE NOT NULL,
  to_date             DATE NOT NULL,
  total_days          NUMBER(6,2) NOT NULL,
  reason              CLOB,
  approval_status     VARCHAR2(30) DEFAULT 'PENDING' NOT NULL,
  approved_by         NUMBER(19) REFERENCES appuser(id),
  approved_at         TIMESTAMP WITH TIME ZONE,
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT chk_leave_dates CHECK (to_date >= from_date)
);

/* ============================================================
   6. ATTENDANCE
   ============================================================ */

CREATE TABLE attendance_devices (
  device_id           NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  branch_id           NUMBER(19) NOT NULL REFERENCES branches(branch_id) ON DELETE CASCADE,
  device_code         VARCHAR2(50) NOT NULL,
  device_name         VARCHAR2(120) NOT NULL,
  device_type         VARCHAR2(50), -- BIOMETRIC, RFID, MOBILE_APP
  ip_address          VARCHAR2(45),
  location_name       VARCHAR2(120),
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uk_attendance_devices UNIQUE (branch_id, device_code)
);

CREATE TABLE student_attendance (
  attendance_id       NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  student_id          NUMBER(19) NOT NULL REFERENCES students(student_id) ON DELETE CASCADE,
  enrollment_id       NUMBER(19) REFERENCES student_enrollments(enrollment_id) ON DELETE SET NULL,
  branch_id           NUMBER(19) NOT NULL REFERENCES branches(branch_id),
  attendance_date     DATE NOT NULL,
  in_time             VARCHAR2(8),
  out_time            VARCHAR2(8),
  attendance_status   VARCHAR2(30) DEFAULT 'PRESENT' NOT NULL, -- PRESENT, ABSENT, LATE, LEAVE, HOLIDAY
  device_id           NUMBER(19) REFERENCES attendance_devices(device_id),
  remarks             CLOB,
  created_by          NUMBER(19) REFERENCES appuser(id),
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uk_student_attendance UNIQUE (student_id, attendance_date)
);

CREATE TABLE employee_attendance (
  attendance_id       NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  employee_id         NUMBER(19) NOT NULL REFERENCES employees(employee_id) ON DELETE CASCADE,
  branch_id           NUMBER(19) REFERENCES branches(branch_id),
  attendance_date     DATE NOT NULL,
  in_time             VARCHAR2(8),
  out_time            VARCHAR2(8),
  attendance_status   VARCHAR2(30) DEFAULT 'PRESENT' NOT NULL,
  device_id           NUMBER(19) REFERENCES attendance_devices(device_id),
  remarks             CLOB,
  created_by          NUMBER(19) REFERENCES appuser(id),
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uk_employee_attendance UNIQUE (employee_id, attendance_date)
);

CREATE TABLE holidays (
  holiday_id          NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  institution_id      NUMBER(19) NOT NULL REFERENCES institutions(institution_id) ON DELETE CASCADE,
  branch_id           NUMBER(19) REFERENCES branches(branch_id) ON DELETE CASCADE,
  holiday_title       VARCHAR2(150) NOT NULL,
  from_date           DATE NOT NULL,
  to_date             DATE NOT NULL,
  holiday_type        VARCHAR2(50), -- Govt, Weekly, Institute
  description         CLOB,
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT chk_holiday_dates CHECK (to_date >= from_date)
);

/* ============================================================
   7. ROUTINE / NOTICE / COMMUNICATION
   ============================================================ */

CREATE TABLE class_routines (
  routine_id          NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  branch_id           NUMBER(19) NOT NULL REFERENCES branches(branch_id) ON DELETE CASCADE,
  academic_year_id    NUMBER(19) NOT NULL REFERENCES academic_years(academic_year_id),
  batch_id            NUMBER(19) NOT NULL REFERENCES academic_batches(batch_id),
  day_name            VARCHAR2(15) NOT NULL, -- SATURDAY, SUNDAY
  period_no           NUMBER(10) NOT NULL,
  start_time          VARCHAR2(8) NOT NULL,
  end_time            VARCHAR2(8) NOT NULL,
  subject_id          NUMBER(19) REFERENCES subjects(subject_id),
  teacher_id          NUMBER(19) REFERENCES employees(employee_id),
  classroom_id        NUMBER(19) REFERENCES classrooms(classroom_id),
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uk_class_routine UNIQUE (batch_id, day_name, period_no)
);

CREATE TABLE notices (
  notice_id           NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  institution_id      NUMBER(19) NOT NULL REFERENCES institutions(institution_id) ON DELETE CASCADE,
  branch_id           NUMBER(19) REFERENCES branches(branch_id) ON DELETE CASCADE,
  notice_title        VARCHAR2(200) NOT NULL,
  notice_body         CLOB NOT NULL,
  audience_type       VARCHAR2(50) DEFAULT 'ALL' NOT NULL, -- ALL, STUDENT, GUARDIAN, TEACHER, STAFF
  publish_date        DATE DEFAULT CURRENT_DATE NOT NULL,
  expire_date         DATE,
  attachment_url      CLOB,
  is_published        NUMBER(1) DEFAULT 0 NOT NULL CHECK (is_published IN (0,1)),
  created_by          NUMBER(19) REFERENCES appuser(id),
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE notification_templates (
  template_id         NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  institution_id      NUMBER(19) REFERENCES institutions(institution_id) ON DELETE CASCADE,
  template_code       VARCHAR2(80) NOT NULL,
  template_name       VARCHAR2(150) NOT NULL,
  channel             VARCHAR2(30) NOT NULL, -- SMS, EMAIL, WHATSAPP, APP
  subject_template    VARCHAR2(250),
  body_template       CLOB NOT NULL,
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  CONSTRAINT uk_notification_templates UNIQUE (institution_id, template_code, channel)
);

CREATE TABLE notification_logs (
  notification_log_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  institution_id      NUMBER(19) REFERENCES institutions(institution_id) ON DELETE CASCADE,
  template_id         NUMBER(19) REFERENCES notification_templates(template_id),
  channel             VARCHAR2(30) NOT NULL,
  recipient_type      VARCHAR2(30),
  recipient_id        NUMBER(19),
  recipient_address   VARCHAR2(200),
  subject_text        VARCHAR2(250),
  body_text           CLOB,
  send_status         VARCHAR2(30) DEFAULT 'PENDING' NOT NULL, -- PENDING, SENT, FAILED
  error_message       CLOB,
  sent_at             TIMESTAMP WITH TIME ZONE,
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

/* ============================================================
   8. FEES MANAGEMENT
   ============================================================ */

CREATE TABLE fee_heads (
  fee_head_id         NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  institution_id      NUMBER(19) NOT NULL REFERENCES institutions(institution_id) ON DELETE CASCADE,
  fee_code            VARCHAR2(30) NOT NULL,
  fee_name            VARCHAR2(120) NOT NULL,
  fee_type            VARCHAR2(30) DEFAULT 'REGULAR' NOT NULL, -- ADMISSION, TUITION, EXAM, TRANSPORT, OTHER
  is_recurring        NUMBER(1) DEFAULT 0 NOT NULL CHECK (is_recurring IN (0,1)),
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  CONSTRAINT uk_fee_heads UNIQUE (institution_id, fee_code)
);

CREATE TABLE fee_structures (
  fee_structure_id    NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  branch_id           NUMBER(19) NOT NULL REFERENCES branches(branch_id) ON DELETE CASCADE,
  academic_year_id    NUMBER(19) NOT NULL REFERENCES academic_years(academic_year_id),
  class_id            NUMBER(19) NOT NULL REFERENCES class_levels(class_id),
  group_id            NUMBER(19) REFERENCES groups(group_id),
  medium_id           NUMBER(19) REFERENCES mediums(medium_id),
  structure_name      VARCHAR2(150) NOT NULL,
  effective_from      DATE NOT NULL,
  effective_to        DATE,
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  created_by          NUMBER(19) REFERENCES appuser(id),
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uk_fee_structures UNIQUE (branch_id, academic_year_id, class_id, group_id, medium_id, structure_name)
);

CREATE TABLE fee_structure_details (
  fee_structure_detail_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  fee_structure_id    NUMBER(19) NOT NULL REFERENCES fee_structures(fee_structure_id) ON DELETE CASCADE,
  fee_head_id         NUMBER(19) NOT NULL REFERENCES fee_heads(fee_head_id),
  amount              NUMBER(12,2) DEFAULT 0 NOT NULL,
  frequency           VARCHAR2(30) DEFAULT 'ONE_TIME' NOT NULL, -- ONE_TIME, MONTHLY, QUARTERLY, YEARLY
  due_day             NUMBER(10),
  is_optional         NUMBER(1) DEFAULT 0 NOT NULL CHECK (is_optional IN (0,1)),
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  CONSTRAINT uk_fee_structure_details UNIQUE (fee_structure_id, fee_head_id),
  CONSTRAINT chk_fee_amount CHECK (amount >= 0)
);

CREATE TABLE student_fee_assignments (
  assignment_id       NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  student_id          NUMBER(19) NOT NULL REFERENCES students(student_id) ON DELETE CASCADE,
  enrollment_id       NUMBER(19) NOT NULL REFERENCES student_enrollments(enrollment_id) ON DELETE CASCADE,
  fee_structure_id    NUMBER(19) NOT NULL REFERENCES fee_structures(fee_structure_id),
  discount_percent    NUMBER(5,2) DEFAULT 0,
  discount_amount     NUMBER(12,2) DEFAULT 0,
  reason              CLOB,
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  assigned_by         NUMBER(19) REFERENCES appuser(id),
  assigned_at         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uk_student_fee_assignment UNIQUE (student_id, enrollment_id, fee_structure_id)
);

CREATE TABLE fee_invoices (
  invoice_id          NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  branch_id           NUMBER(19) NOT NULL REFERENCES branches(branch_id),
  student_id          NUMBER(19) NOT NULL REFERENCES students(student_id),
  enrollment_id       NUMBER(19) REFERENCES student_enrollments(enrollment_id),
  invoice_no          VARCHAR2(50) NOT NULL,
  invoice_date        DATE DEFAULT CURRENT_DATE NOT NULL,
  due_date            DATE,
  billing_month       NUMBER(10),
  billing_year        NUMBER(10),
  gross_amount        NUMBER(12,2) DEFAULT 0 NOT NULL,
  discount_amount     NUMBER(12,2) DEFAULT 0 NOT NULL,
  fine_amount         NUMBER(12,2) DEFAULT 0 NOT NULL,
  net_amount          NUMBER(12,2) DEFAULT 0 NOT NULL,
  paid_amount         NUMBER(12,2) DEFAULT 0 NOT NULL,
  due_amount          NUMBER(12,2) DEFAULT 0 NOT NULL,
  invoice_status      VARCHAR2(30) DEFAULT 'UNPAID' NOT NULL, -- UNPAID, PARTIAL, PAID, CANCELLED
  remarks             CLOB,
  created_by          NUMBER(19) REFERENCES appuser(id),
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uk_fee_invoices_no UNIQUE (branch_id, invoice_no)
);

CREATE TABLE fee_invoice_lines (
  invoice_line_id     NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  invoice_id          NUMBER(19) NOT NULL REFERENCES fee_invoices(invoice_id) ON DELETE CASCADE,
  fee_head_id         NUMBER(19) NOT NULL REFERENCES fee_heads(fee_head_id),
  description         VARCHAR2(200),
  amount              NUMBER(12,2) DEFAULT 0 NOT NULL,
  discount_amount     NUMBER(12,2) DEFAULT 0 NOT NULL,
  fine_amount         NUMBER(12,2) DEFAULT 0 NOT NULL,
  net_amount          NUMBER(12,2) DEFAULT 0 NOT NULL,
  paid_amount         NUMBER(12,2) DEFAULT 0 NOT NULL,
  due_amount          NUMBER(12,2) DEFAULT 0 NOT NULL,
  line_status         VARCHAR2(30) DEFAULT 'UNPAID' NOT NULL
);

CREATE TABLE fee_collections (
  collection_id       NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  branch_id           NUMBER(19) NOT NULL REFERENCES branches(branch_id),
  student_id          NUMBER(19) NOT NULL REFERENCES students(student_id),
  receipt_no          VARCHAR2(50) NOT NULL,
  collection_date     DATE DEFAULT CURRENT_DATE NOT NULL,
  payment_method      VARCHAR2(30) DEFAULT 'CASH' NOT NULL, -- CASH, BANK, BKASH, NAGAD, CARD
  reference_no        VARCHAR2(100),
  total_amount        NUMBER(12,2) DEFAULT 0 NOT NULL,
  remarks             CLOB,
  collected_by        NUMBER(19) REFERENCES appuser(id),
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uk_fee_receipt_no UNIQUE (branch_id, receipt_no)
);

CREATE TABLE fee_collection_lines (
  collection_line_id  NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  collection_id       NUMBER(19) NOT NULL REFERENCES fee_collections(collection_id) ON DELETE CASCADE,
  invoice_id          NUMBER(19) NOT NULL REFERENCES fee_invoices(invoice_id),
  invoice_line_id     NUMBER(19) REFERENCES fee_invoice_lines(invoice_line_id),
  paid_amount         NUMBER(12,2) DEFAULT 0 NOT NULL,
  discount_amount     NUMBER(12,2) DEFAULT 0 NOT NULL,
  fine_amount         NUMBER(12,2) DEFAULT 0 NOT NULL
);

CREATE TABLE fee_waivers (
  waiver_id           NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  student_id          NUMBER(19) NOT NULL REFERENCES students(student_id) ON DELETE CASCADE,
  fee_head_id         NUMBER(19) REFERENCES fee_heads(fee_head_id),
  waiver_type         VARCHAR2(30) NOT NULL, -- PERCENT, FIXED
  waiver_value        NUMBER(12,2) NOT NULL,
  effective_from      DATE NOT NULL,
  effective_to        DATE,
  approval_status     VARCHAR2(30) DEFAULT 'PENDING' NOT NULL,
  approved_by         NUMBER(19) REFERENCES appuser(id),
  remarks             CLOB,
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

/* ============================================================
   9. ACCOUNTING CORE
   ============================================================ */

CREATE TABLE fiscal_years (
  fiscal_year_id      NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  institution_id      NUMBER(19) NOT NULL REFERENCES institutions(institution_id) ON DELETE CASCADE,
  year_name           VARCHAR2(30) NOT NULL,
  start_date          DATE NOT NULL,
  end_date            DATE NOT NULL,
  is_current          NUMBER(1) DEFAULT 0 NOT NULL CHECK (is_current IN (0,1)),
  status              VARCHAR2(20) DEFAULT 'OPEN' NOT NULL, -- OPEN, CLOSED
  CONSTRAINT uk_fiscal_years UNIQUE (institution_id, year_name),
  CONSTRAINT chk_fiscal_year_dates CHECK (end_date >= start_date)
);

CREATE TABLE chart_of_accounts (
  account_id          NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  institution_id      NUMBER(19) NOT NULL REFERENCES institutions(institution_id) ON DELETE CASCADE,
  parent_account_id   NUMBER(19) REFERENCES chart_of_accounts(account_id) ON DELETE SET NULL,
  account_code        VARCHAR2(50) NOT NULL,
  account_name        VARCHAR2(150) NOT NULL,
  account_type        VARCHAR2(30) NOT NULL, -- ASSET, LIABILITY, EQUITY, INCOME, EXPENSE
  is_postable         NUMBER(1) DEFAULT 1 NOT NULL CHECK (is_postable IN (0,1)),
  opening_balance     NUMBER(14,2) DEFAULT 0 NOT NULL,
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uk_chart_accounts UNIQUE (institution_id, account_code)
);

CREATE TABLE bank_accounts (
  bank_account_id     NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  institution_id      NUMBER(19) NOT NULL REFERENCES institutions(institution_id) ON DELETE CASCADE,
  branch_id           NUMBER(19) REFERENCES branches(branch_id),
  account_id          NUMBER(19) REFERENCES chart_of_accounts(account_id),
  bank_name           VARCHAR2(120) NOT NULL,
  branch_name         VARCHAR2(120),
  account_name        VARCHAR2(150) NOT NULL,
  account_no          VARCHAR2(80) NOT NULL,
  routing_no          VARCHAR2(50),
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uk_bank_accounts UNIQUE (institution_id, account_no)
);

CREATE TABLE journal_vouchers (
  voucher_id          NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  institution_id      NUMBER(19) NOT NULL REFERENCES institutions(institution_id) ON DELETE CASCADE,
  branch_id           NUMBER(19) REFERENCES branches(branch_id),
  fiscal_year_id      NUMBER(19) REFERENCES fiscal_years(fiscal_year_id),
  voucher_no          VARCHAR2(50) NOT NULL,
  voucher_date        DATE DEFAULT CURRENT_DATE NOT NULL,
  voucher_type        VARCHAR2(30) DEFAULT 'JOURNAL' NOT NULL, -- JOURNAL, RECEIPT, PAYMENT, CONTRA
  source_module       VARCHAR2(50), -- FEES, PAYROLL, INVENTORY
  source_id           NUMBER(19),
  narration           CLOB,
  total_debit         NUMBER(14,2) DEFAULT 0 NOT NULL,
  total_credit        NUMBER(14,2) DEFAULT 0 NOT NULL,
  approval_status     VARCHAR2(30) DEFAULT 'DRAFT' NOT NULL,
  created_by          NUMBER(19) REFERENCES appuser(id),
  approved_by         NUMBER(19) REFERENCES appuser(id),
  approved_at         TIMESTAMP WITH TIME ZONE,
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uk_journal_vouchers UNIQUE (institution_id, voucher_no),
  CONSTRAINT chk_journal_balance CHECK (total_debit = total_credit)
);

CREATE TABLE journal_lines (
  journal_line_id     NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  voucher_id          NUMBER(19) NOT NULL REFERENCES journal_vouchers(voucher_id) ON DELETE CASCADE,
  account_id          NUMBER(19) NOT NULL REFERENCES chart_of_accounts(account_id),
  debit_amount        NUMBER(14,2) DEFAULT 0 NOT NULL,
  credit_amount       NUMBER(14,2) DEFAULT 0 NOT NULL,
  line_description    CLOB,
  cost_center         VARCHAR2(80),
  CONSTRAINT chk_journal_line_amount CHECK (
    (debit_amount > 0 AND credit_amount = 0) OR (credit_amount > 0 AND debit_amount = 0)
  )
);

/* ============================================================
   10. EXAM / MARKS / RESULT
   ============================================================ */

CREATE TABLE exam_types (
  exam_type_id        NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  institution_id      NUMBER(19) NOT NULL REFERENCES institutions(institution_id) ON DELETE CASCADE,
  exam_type_code      VARCHAR2(30) NOT NULL,
  exam_type_name      VARCHAR2(120) NOT NULL, -- Half Yearly, Annual, Class Test
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  CONSTRAINT uk_exam_types UNIQUE (institution_id, exam_type_code)
);

CREATE TABLE exams (
  exam_id             NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  branch_id           NUMBER(19) NOT NULL REFERENCES branches(branch_id) ON DELETE CASCADE,
  academic_year_id    NUMBER(19) NOT NULL REFERENCES academic_years(academic_year_id),
  exam_type_id        NUMBER(19) NOT NULL REFERENCES exam_types(exam_type_id),
  exam_name           VARCHAR2(150) NOT NULL,
  class_id            NUMBER(19) REFERENCES class_levels(class_id),
  start_date          DATE,
  end_date            DATE,
  result_publish_date DATE,
  exam_status         VARCHAR2(30) DEFAULT 'DRAFT' NOT NULL, -- DRAFT, RUNNING, COMPLETED, PUBLISHED
  created_by          NUMBER(19) REFERENCES appuser(id),
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uk_exams UNIQUE (branch_id, academic_year_id, exam_type_id, exam_name, class_id)
);

CREATE TABLE exam_subjects (
  exam_subject_id     NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  exam_id             NUMBER(19) NOT NULL REFERENCES exams(exam_id) ON DELETE CASCADE,
  subject_id          NUMBER(19) NOT NULL REFERENCES subjects(subject_id),
  full_marks          NUMBER(8,2) DEFAULT 100 NOT NULL,
  pass_marks          NUMBER(8,2) DEFAULT 33 NOT NULL,
  exam_date           DATE,
  start_time          VARCHAR2(8),
  end_time            VARCHAR2(8),
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  CONSTRAINT uk_exam_subjects UNIQUE (exam_id, subject_id)
);

CREATE TABLE mark_components (
  component_id        NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  institution_id      NUMBER(19) NOT NULL REFERENCES institutions(institution_id) ON DELETE CASCADE,
  component_code      VARCHAR2(30) NOT NULL,
  component_name      VARCHAR2(100) NOT NULL, -- Written, MCQ, Practical, Viva
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  CONSTRAINT uk_mark_components UNIQUE (institution_id, component_code)
);

CREATE TABLE exam_subject_components (
  exam_subject_component_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  exam_subject_id     NUMBER(19) NOT NULL REFERENCES exam_subjects(exam_subject_id) ON DELETE CASCADE,
  component_id        NUMBER(19) NOT NULL REFERENCES mark_components(component_id),
  full_marks          NUMBER(8,2) NOT NULL,
  pass_marks          NUMBER(8,2) DEFAULT 0,
  sort_order          NUMBER(10) DEFAULT 0,
  CONSTRAINT uk_exam_subject_components UNIQUE (exam_subject_id, component_id)
);

CREATE TABLE exam_marks (
  mark_id             NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  exam_id             NUMBER(19) NOT NULL REFERENCES exams(exam_id) ON DELETE CASCADE,
  exam_subject_id     NUMBER(19) NOT NULL REFERENCES exam_subjects(exam_subject_id) ON DELETE CASCADE,
  student_id          NUMBER(19) NOT NULL REFERENCES students(student_id) ON DELETE CASCADE,
  component_id        NUMBER(19) REFERENCES mark_components(component_id),
  marks_obtained      NUMBER(8,2) DEFAULT 0 NOT NULL,
  is_absent           NUMBER(1) DEFAULT 0 NOT NULL CHECK (is_absent IN (0,1)),
  remarks             CLOB,
  entered_by          NUMBER(19) REFERENCES appuser(id),
  entered_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uk_exam_marks UNIQUE (exam_subject_id, student_id, component_id)
);

CREATE TABLE grading_scales (
  grading_scale_id    NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  institution_id      NUMBER(19) NOT NULL REFERENCES institutions(institution_id) ON DELETE CASCADE,
  scale_name          VARCHAR2(100) NOT NULL, -- GPA 5, GPA 4
  max_gpa             NUMBER(4,2) DEFAULT 5 NOT NULL,
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  CONSTRAINT uk_grading_scales UNIQUE (institution_id, scale_name)
);

CREATE TABLE grading_scale_details (
  grade_detail_id     NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  grading_scale_id    NUMBER(19) NOT NULL REFERENCES grading_scales(grading_scale_id) ON DELETE CASCADE,
  min_marks           NUMBER(8,2) NOT NULL,
  max_marks           NUMBER(8,2) NOT NULL,
  letter_grade        VARCHAR2(10) NOT NULL,
  grade_point         NUMBER(4,2) NOT NULL,
  remarks             VARCHAR2(100),
  CONSTRAINT chk_grade_marks CHECK (max_marks >= min_marks)
);

CREATE TABLE student_results (
  result_id           NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  exam_id             NUMBER(19) NOT NULL REFERENCES exams(exam_id) ON DELETE CASCADE,
  student_id          NUMBER(19) NOT NULL REFERENCES students(student_id) ON DELETE CASCADE,
  enrollment_id       NUMBER(19) REFERENCES student_enrollments(enrollment_id),
  total_marks         NUMBER(10,2) DEFAULT 0 NOT NULL,
  obtained_marks      NUMBER(10,2) DEFAULT 0 NOT NULL,
  gpa                 NUMBER(4,2),
  letter_grade        VARCHAR2(10),
  merit_position      NUMBER(10),
  result_status       VARCHAR2(30) DEFAULT 'PENDING' NOT NULL, -- PASSED, FAILED, ABSENT, PENDING
  failed_subject_count NUMBER(10) DEFAULT 0 NOT NULL,
  published_at        TIMESTAMP WITH TIME ZONE,
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uk_student_results UNIQUE (exam_id, student_id)
);

CREATE TABLE student_result_details (
  result_detail_id    NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  result_id           NUMBER(19) NOT NULL REFERENCES student_results(result_id) ON DELETE CASCADE,
  subject_id          NUMBER(19) NOT NULL REFERENCES subjects(subject_id),
  full_marks          NUMBER(8,2) DEFAULT 100 NOT NULL,
  pass_marks          NUMBER(8,2) DEFAULT 33 NOT NULL,
  obtained_marks      NUMBER(8,2) DEFAULT 0 NOT NULL,
  letter_grade        VARCHAR2(10),
  grade_point         NUMBER(4,2),
  subject_status      VARCHAR2(30) DEFAULT 'PENDING' NOT NULL, -- PASSED, FAILED, ABSENT
  remarks             CLOB,
  CONSTRAINT uk_student_result_details UNIQUE (result_id, subject_id)
);

/* ============================================================
   11. LIBRARY MANAGEMENT
   ============================================================ */

CREATE TABLE book_categories (
  book_category_id    NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  institution_id      NUMBER(19) NOT NULL REFERENCES institutions(institution_id) ON DELETE CASCADE,
  category_name       VARCHAR2(120) NOT NULL,
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  CONSTRAINT uk_book_categories UNIQUE (institution_id, category_name)
);

CREATE TABLE books (
  book_id             NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  institution_id      NUMBER(19) NOT NULL REFERENCES institutions(institution_id) ON DELETE CASCADE,
  book_category_id    NUMBER(19) REFERENCES book_categories(book_category_id),
  isbn                VARCHAR2(80),
  book_title          VARCHAR2(250) NOT NULL,
  author_name         VARCHAR2(200),
  publisher_name      VARCHAR2(200),
  edition             VARCHAR2(80),
  publish_year        NUMBER(10),
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE book_copies (
  book_copy_id        NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  book_id             NUMBER(19) NOT NULL REFERENCES books(book_id) ON DELETE CASCADE,
  branch_id           NUMBER(19) REFERENCES branches(branch_id),
  accession_no        VARCHAR2(80) NOT NULL,
  shelf_no            VARCHAR2(50),
  purchase_date       DATE,
  purchase_price      NUMBER(10,2),
  copy_status         VARCHAR2(30) DEFAULT 'AVAILABLE' NOT NULL, -- AVAILABLE, ISSUED, LOST, DAMAGED
  CONSTRAINT uk_book_copies UNIQUE (accession_no)
);

CREATE TABLE library_issues (
  issue_id            NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  book_copy_id        NUMBER(19) NOT NULL REFERENCES book_copies(book_copy_id),
  member_type         VARCHAR2(30) NOT NULL, -- STUDENT, EMPLOYEE
  student_id          NUMBER(19) REFERENCES students(student_id),
  employee_id         NUMBER(19) REFERENCES employees(employee_id),
  issue_date          DATE DEFAULT CURRENT_DATE NOT NULL,
  due_date            DATE NOT NULL,
  return_date         DATE,
  issue_status        VARCHAR2(30) DEFAULT 'ISSUED' NOT NULL, -- ISSUED, RETURNED, LOST
  fine_amount         NUMBER(10,2) DEFAULT 0 NOT NULL,
  issued_by           NUMBER(19) REFERENCES appuser(id),
  returned_by         NUMBER(19) REFERENCES appuser(id),
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

/* ============================================================
   12. TRANSPORT MANAGEMENT
   ============================================================ */

CREATE TABLE vehicles (
  vehicle_id          NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  institution_id      NUMBER(19) NOT NULL REFERENCES institutions(institution_id) ON DELETE CASCADE,
  vehicle_no          VARCHAR2(50) NOT NULL,
  vehicle_type        VARCHAR2(50),
  capacity            NUMBER(10),
  driver_name         VARCHAR2(150),
  driver_mobile       VARCHAR2(30),
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uk_vehicles UNIQUE (institution_id, vehicle_no)
);

CREATE TABLE transport_routes (
  route_id            NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  branch_id           NUMBER(19) NOT NULL REFERENCES branches(branch_id) ON DELETE CASCADE,
  route_code          VARCHAR2(30) NOT NULL,
  route_name          VARCHAR2(150) NOT NULL,
  vehicle_id          NUMBER(19) REFERENCES vehicles(vehicle_id),
  monthly_fee         NUMBER(12,2) DEFAULT 0 NOT NULL,
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  CONSTRAINT uk_transport_routes UNIQUE (branch_id, route_code)
);

CREATE TABLE transport_stops (
  stop_id             NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  route_id            NUMBER(19) NOT NULL REFERENCES transport_routes(route_id) ON DELETE CASCADE,
  stop_name           VARCHAR2(150) NOT NULL,
  stop_order          NUMBER(10) DEFAULT 0,
  pickup_time         VARCHAR2(8),
  drop_time           VARCHAR2(8),
  stop_fee            NUMBER(12,2) DEFAULT 0,
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL
);

CREATE TABLE student_transport_assignments (
  transport_assignment_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  student_id          NUMBER(19) NOT NULL REFERENCES students(student_id) ON DELETE CASCADE,
  route_id            NUMBER(19) NOT NULL REFERENCES transport_routes(route_id),
  stop_id             NUMBER(19) REFERENCES transport_stops(stop_id),
  start_date          DATE DEFAULT CURRENT_DATE NOT NULL,
  end_date            DATE,
  monthly_fee         NUMBER(12,2) DEFAULT 0 NOT NULL,
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

/* ============================================================
   13. INVENTORY / PROCUREMENT BASIC
   ============================================================ */

CREATE TABLE vendors (
  vendor_id           NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  institution_id      NUMBER(19) NOT NULL REFERENCES institutions(institution_id) ON DELETE CASCADE,
  vendor_code         VARCHAR2(30) NOT NULL,
  vendor_name         VARCHAR2(150) NOT NULL,
  contact_person      VARCHAR2(150),
  mobile              VARCHAR2(30),
  email               VARCHAR2(150),
  address_line        CLOB,
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uk_vendors UNIQUE (institution_id, vendor_code)
);

CREATE TABLE item_categories (
  item_category_id    NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  institution_id      NUMBER(19) NOT NULL REFERENCES institutions(institution_id) ON DELETE CASCADE,
  category_name       VARCHAR2(120) NOT NULL,
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  CONSTRAINT uk_item_categories UNIQUE (institution_id, category_name)
);

CREATE TABLE items (
  item_id             NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  institution_id      NUMBER(19) NOT NULL REFERENCES institutions(institution_id) ON DELETE CASCADE,
  item_category_id    NUMBER(19) REFERENCES item_categories(item_category_id),
  item_code           VARCHAR2(50) NOT NULL,
  item_name           VARCHAR2(150) NOT NULL,
  unit_name           VARCHAR2(30) DEFAULT 'PCS' NOT NULL,
  reorder_level       NUMBER(12,2) DEFAULT 0,
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uk_items UNIQUE (institution_id, item_code)
);

CREATE TABLE stock_locations (
  location_id         NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  branch_id           NUMBER(19) NOT NULL REFERENCES branches(branch_id) ON DELETE CASCADE,
  location_code       VARCHAR2(30) NOT NULL,
  location_name       VARCHAR2(120) NOT NULL,
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  CONSTRAINT uk_stock_locations UNIQUE (branch_id, location_code)
);

CREATE TABLE purchase_orders (
  po_id               NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  branch_id           NUMBER(19) NOT NULL REFERENCES branches(branch_id),
  vendor_id           NUMBER(19) REFERENCES vendors(vendor_id),
  po_no               VARCHAR2(50) NOT NULL,
  po_date             DATE DEFAULT CURRENT_DATE NOT NULL,
  expected_date       DATE,
  total_amount        NUMBER(14,2) DEFAULT 0 NOT NULL,
  po_status           VARCHAR2(30) DEFAULT 'DRAFT' NOT NULL, -- DRAFT, APPROVED, RECEIVED, CANCELLED
  created_by          NUMBER(19) REFERENCES appuser(id),
  approved_by         NUMBER(19) REFERENCES appuser(id),
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uk_purchase_orders UNIQUE (branch_id, po_no)
);

CREATE TABLE purchase_order_lines (
  po_line_id          NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  po_id               NUMBER(19) NOT NULL REFERENCES purchase_orders(po_id) ON DELETE CASCADE,
  item_id             NUMBER(19) NOT NULL REFERENCES items(item_id),
  quantity            NUMBER(12,2) DEFAULT 0 NOT NULL,
  rate                NUMBER(12,2) DEFAULT 0 NOT NULL,
  amount              NUMBER(14,2) DEFAULT 0 NOT NULL,
  remarks             CLOB
);

CREATE TABLE stock_transactions (
  stock_transaction_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  branch_id           NUMBER(19) NOT NULL REFERENCES branches(branch_id),
  location_id         NUMBER(19) REFERENCES stock_locations(location_id),
  item_id             NUMBER(19) NOT NULL REFERENCES items(item_id),
  transaction_date    DATE DEFAULT CURRENT_DATE NOT NULL,
  transaction_type    VARCHAR2(30) NOT NULL, -- IN, OUT, ADJUSTMENT
  source_module       VARCHAR2(50),
  source_id           NUMBER(19),
  quantity            NUMBER(12,2) NOT NULL,
  rate                NUMBER(12,2) DEFAULT 0,
  amount              NUMBER(14,2) DEFAULT 0,
  remarks             CLOB,
  created_by          NUMBER(19) REFERENCES appuser(id),
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

/* ============================================================
   14. HOSTEL BASIC
   ============================================================ */

CREATE TABLE hostels (
  hostel_id           NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  branch_id           NUMBER(19) NOT NULL REFERENCES branches(branch_id) ON DELETE CASCADE,
  hostel_name         VARCHAR2(150) NOT NULL,
  hostel_type         VARCHAR2(30), -- BOYS, GIRLS
  address_line        CLOB,
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  CONSTRAINT uk_hostels UNIQUE (branch_id, hostel_name)
);

CREATE TABLE hostel_rooms (
  hostel_room_id      NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  hostel_id           NUMBER(19) NOT NULL REFERENCES hostels(hostel_id) ON DELETE CASCADE,
  room_no             VARCHAR2(50) NOT NULL,
  capacity            NUMBER(10) DEFAULT 1 NOT NULL,
  monthly_fee         NUMBER(12,2) DEFAULT 0 NOT NULL,
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  CONSTRAINT uk_hostel_rooms UNIQUE (hostel_id, room_no)
);

CREATE TABLE student_hostel_assignments (
  hostel_assignment_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  student_id          NUMBER(19) NOT NULL REFERENCES students(student_id) ON DELETE CASCADE,
  hostel_room_id      NUMBER(19) NOT NULL REFERENCES hostel_rooms(hostel_room_id),
  start_date          DATE DEFAULT CURRENT_DATE NOT NULL,
  end_date            DATE,
  monthly_fee         NUMBER(12,2) DEFAULT 0 NOT NULL,
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

/* ============================================================
   15. SYSTEM SETTINGS / FILES / AUDIT
   ============================================================ */

CREATE TABLE system_settings (
  setting_id          NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  institution_id      NUMBER(19) REFERENCES institutions(institution_id) ON DELETE CASCADE,
  branch_id           NUMBER(19) REFERENCES branches(branch_id) ON DELETE CASCADE,
  setting_key         VARCHAR2(100) NOT NULL,
  setting_value       CLOB,
  setting_group       VARCHAR2(80),
  is_encrypted        NUMBER(1) DEFAULT 0 NOT NULL CHECK (is_encrypted IN (0,1)),
  updated_by          NUMBER(19) REFERENCES appuser(id),
  updated_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uk_system_settings UNIQUE (institution_id, branch_id, setting_key)
);

CREATE TABLE file_attachments (
  attachment_id       NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  institution_id      NUMBER(19) REFERENCES institutions(institution_id) ON DELETE CASCADE,
  module_name         VARCHAR2(80) NOT NULL,
  record_id           NUMBER(19) NOT NULL,
  file_name           VARCHAR2(250) NOT NULL,
  file_url            CLOB NOT NULL,
  file_type           VARCHAR2(80),
  file_size_bytes     NUMBER(19),
  uploaded_by         NUMBER(19) REFERENCES appuser(id),
  uploaded_at         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL
);

CREATE TABLE audit_logs (
  audit_log_id        NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  institution_id      NUMBER(19) REFERENCES institutions(institution_id) ON DELETE CASCADE,
  id             NUMBER(19) REFERENCES appuser(id) ON DELETE SET NULL,
  table_name          VARCHAR2(120) NOT NULL,
  record_id           NUMBER(19),
  action_type         VARCHAR2(30) NOT NULL, -- INSERT, UPDATE, DELETE, LOGIN, APPROVE
  old_data            CLOB CHECK (old_data IS JSON),
  new_data            CLOB CHECK (new_data IS JSON),
  ip_address          VARCHAR2(45),
  user_agent          CLOB,
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

/* ============================================================
   16. INDEXES FOR PERFORMANCE
   ============================================================ */

CREATE INDEX idx_branches_institution ON branches(institution_id);
CREATE INDEX idx_users_inst_branch ON appuser(institution_id, branch_id);
CREATE INDEX idx_students_inst_status ON students(institution_id, status);
-- PostgreSQL GIN full-text index converted to a normal Oracle b-tree index.
-- For Oracle Text search, create a CTXSYS.CONTEXT index after adding a generated/search column.
CREATE INDEX idx_students_name ON students(first_name, last_name);
CREATE INDEX idx_student_enrollments_student ON student_enrollments(student_id);
CREATE INDEX idx_student_enrollments_batch ON student_enrollments(batch_id);
CREATE INDEX idx_student_attendance_date ON student_attendance(branch_id, attendance_date);
CREATE INDEX idx_employee_attendance_date ON employee_attendance(branch_id, attendance_date);
CREATE INDEX idx_fee_invoices_student ON fee_invoices(student_id, invoice_status);
CREATE INDEX idx_fee_invoices_date ON fee_invoices(branch_id, invoice_date);
CREATE INDEX idx_fee_collections_student ON fee_collections(student_id, collection_date);
CREATE INDEX idx_exam_marks_student ON exam_marks(student_id, exam_id);
CREATE INDEX idx_journal_voucher_date ON journal_vouchers(institution_id, voucher_date);
CREATE INDEX idx_audit_logs_table_record ON audit_logs(table_name, record_id);
CREATE INDEX idx_notification_logs_status ON notification_logs(send_status, created_at);

/* ============================================================
   17. UPDATED_AT TRIGGERS
   ============================================================ */

CREATE OR REPLACE TRIGGER trg_institutions_updated_at
BEFORE UPDATE ON institutions
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER trg_branches_updated_at
BEFORE UPDATE ON branches
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER trg_academic_years_updated_at
BEFORE UPDATE ON academic_years
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER trg_academic_sessions_updated_at
BEFORE UPDATE ON academic_sessions
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER trg_appuser_updated_at
BEFORE UPDATE ON appuser
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER trg_roles_updated_at
BEFORE UPDATE ON roles
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER trg_class_levels_updated_at
BEFORE UPDATE ON class_levels
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER trg_academic_batches_updated_at
BEFORE UPDATE ON academic_batches
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER trg_students_updated_at
BEFORE UPDATE ON students
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER trg_student_admissions_updated_at
BEFORE UPDATE ON student_admissions
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER trg_guardians_updated_at
BEFORE UPDATE ON guardians
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER trg_student_addresses_updated_at
BEFORE UPDATE ON student_addresses
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER trg_student_enrollments_updated_at
BEFORE UPDATE ON student_enrollments
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER trg_promotions_updated_at
BEFORE UPDATE ON promotions
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER trg_employees_updated_at
BEFORE UPDATE ON employees
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER trg_employee_addresses_updated_at
BEFORE UPDATE ON employee_addresses
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER trg_employee_leave_updated_at
BEFORE UPDATE ON employee_leave_applications
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER trg_student_attendance_updated_at
BEFORE UPDATE ON student_attendance
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER trg_employee_attendance_updated_at
BEFORE UPDATE ON employee_attendance
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER trg_class_routines_updated_at
BEFORE UPDATE ON class_routines
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER trg_notices_updated_at
BEFORE UPDATE ON notices
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER trg_fee_structures_updated_at
BEFORE UPDATE ON fee_structures
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER trg_fee_invoices_updated_at
BEFORE UPDATE ON fee_invoices
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER trg_fee_collections_updated_at
BEFORE UPDATE ON fee_collections
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER trg_fee_waivers_updated_at
BEFORE UPDATE ON fee_waivers
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER trg_chart_accounts_updated_at
BEFORE UPDATE ON chart_of_accounts
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER trg_journal_vouchers_updated_at
BEFORE UPDATE ON journal_vouchers
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER trg_exams_updated_at
BEFORE UPDATE ON exams
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER trg_exam_marks_updated_at
BEFORE UPDATE ON exam_marks
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER trg_student_results_updated_at
BEFORE UPDATE ON student_results
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER trg_books_updated_at
BEFORE UPDATE ON books
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER trg_library_issues_updated_at
BEFORE UPDATE ON library_issues
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER trg_vehicles_updated_at
BEFORE UPDATE ON vehicles
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER trg_vendors_updated_at
BEFORE UPDATE ON vendors
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER trg_items_updated_at
BEFORE UPDATE ON items
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER trg_purchase_orders_updated_at
BEFORE UPDATE ON purchase_orders
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/

COMMIT;

/* ============================================================
   BASIC CHECK QUERY
   ============================================================ */

-- SELECT table_name
-- FROM user_tables
-- ORDER BY table_name;