/* Formatted on 5/13/2026 9:22:16 AM (QP5 v5.362) */
CREATE TABLE EDUMAN.APPUSER
(
    ID            NUMBER,
    USERNAME      VARCHAR2 (50 BYTE),
    FIRSTNAME     VARCHAR2 (50 BYTE),
    LASTNAME      VARCHAR2 (50 BYTE),
    EMAIL         VARCHAR2 (100 BYTE),
    PASS          VARCHAR2 (100 BYTE),
    ENT_BY        NUMBER,
    ENT_DATE      DATE,
    UPD_BY        NUMBER,
    UPD_DATE      DATE,
    COM_ID        NUMBER,
    USER_GROUP    NUMBER,
    STATUS        VARCHAR2 (1 BYTE) DEFAULT 'A'
);
/

ALTER TABLE APPUSER
    ADD (CONSTRAINT APPUSER_PK PRIMARY KEY (ID),
         CONSTRAINT APPUSER_U01 UNIQUE (USERNAME),
         CONSTRAINT APPUSER_U02 UNIQUE (EMAIL));


ALTER TABLE APPUSER
    ADD (
        CONSTRAINT APPUSER_R01 FOREIGN KEY (USER_GROUP)
            REFERENCES USER_GROUP (ID)
            ENABLE VALIDATE);