/* Formatted on 5/13/2026 9:40:03 AM (QP5 v5.362) */
ALTER TABLE appuser
    ADD (
        password_hash VARCHAR2 (128),
        password_salt VARCHAR2 (64),
        password_algo VARCHAR2 (30) DEFAULT 'HMAC_SH512_V1',
        password_changed_at DATE,
        failed_login_count NUMBER DEFAULT 0,
        locked_until DATE,
        force_pwd_change VARCHAR2 (1) DEFAULT 'N',
        CONSTRAINT appuser_force_pwd_ck CHECK
            (force_pwd_change IN ('Y', 'N')));

CREATE UNIQUE INDEX appuser_uk_username_lwr
    ON appuser (LOWER (username));

CREATE UNIQUE INDEX appuser_uk_email_lwr
    ON appuser (LOWER (email));

CREATE TABLE appuser_pwd_reset
(
    reset_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id        NUMBER NOT NULL,
    otp_hash       VARCHAR2 (128) NOT NULL,
    otp_salt       VARCHAR2 (64) NOT NULL,
    status         VARCHAR2 (1) DEFAULT 'N' NOT NULL,
    attempts       NUMBER DEFAULT 0 NOT NULL,
    created_at     DATE DEFAULT SYSDATE NOT NULL,
    expires_at     DATE NOT NULL,
    verified_at    DATE,
    used_at        DATE,
    request_ip     VARCHAR2 (100),
    user_agent     VARCHAR2 (500),
    CONSTRAINT appuser_pwd_reset_pk PRIMARY KEY (reset_id),
    CONSTRAINT appuser_pwd_reset_user_fk FOREIGN KEY (user_id)
        REFERENCES appuser (id),
    CONSTRAINT appuser_pwd_reset_status_ck CHECK
        (status IN ('N',
                    'V',
                    'U',
                    'E',
                    'L'))
);

/*
N = New OTP
V = Verified OTP
U = Used after password reset
E = Expired
L = Locked due to too many wrong attempts
*/

CREATE INDEX appuser_pwd_reset_i01
    ON appuser_pwd_reset (user_id, status, expires_at);

CREATE OR REPLACE PACKAGE app_auth_pkg
AS
    FUNCTION gen_salt
        RETURN VARCHAR2;

    FUNCTION hash_secret (p_value IN VARCHAR2, p_salt IN VARCHAR2)
        RETURN VARCHAR2;

    PROCEDURE set_password (p_user_id IN NUMBER, p_password IN VARCHAR2);

    FUNCTION authenticate (p_username IN VARCHAR2, p_password IN VARCHAR2)
        RETURN BOOLEAN;

    FUNCTION request_password_reset (p_login IN VARCHAR2)
        RETURN NUMBER;

    FUNCTION verify_reset_otp (p_reset_id IN NUMBER, p_otp IN VARCHAR2)
        RETURN BOOLEAN;

    PROCEDURE reset_password (p_reset_id       IN NUMBER,
                              p_new_password   IN VARCHAR2);
END app_auth_pkg;
/