CREATE TABLE DEPAT_HEAD
(
  EMPCODE      VARCHAR2(15 BYTE),
  E_NAME       VARCHAR2(150 BYTE),
  DEPT_NAME    VARCHAR2(100 BYTE),
  UNIT         VARCHAR2(50 BYTE),
  CREATE_BY    VARCHAR2(100 BYTE),
  CREATE_DATE  DATE,
  MIMETYPE     VARCHAR2(250 BYTE),
  FILENAME     VARCHAR2(255 BYTE),
  LAST_UPDATE  DATE,
  IMAGE        BLOB,
  ID           NUMBER
);

ALTER TABLE DBMIS.DEPAT_HEAD ADD (
  CONSTRAINT DEPAT_HEAD_PK
  PRIMARY KEY
  (ID)
  USING INDEX DBMIS.DEPAT_HEAD_PK
  ENABLE VALIDATE);
SET DEFINE OFF;
Insert into DEPAT_HEAD
   (EMPCODE, E_NAME, DEPT_NAME, UNIT, CREATE_BY, 
    CREATE_DATE, MIMETYPE, FILENAME, LAST_UPDATE, ID)
 Values
   ('IPI-000800', 'MD. SHAHIDUL ISLAM BHUIYAN', 'Legal Affairs and Estate', 'Pharma', 'IPI-009129', 
    TO_DATE('9/1/2025', 'MM/DD/YYYY'), '3', NULL, NULL, 3);
Insert into DEPAT_HEAD
   (EMPCODE, E_NAME, DEPT_NAME, UNIT, CREATE_BY, 
    CREATE_DATE, MIMETYPE, FILENAME, LAST_UPDATE, ID)
 Values
   ('IPI-001014', 'MD. ABDUR RAKIB', 'Internal Audit and Compliance', 'Pharma', 'IPI-009129', 
    TO_DATE('9/1/2025', 'MM/DD/YYYY'), '4', NULL, NULL, 4);
Insert into DEPAT_HEAD
   (EMPCODE, E_NAME, DEPT_NAME, UNIT, CREATE_BY, 
    CREATE_DATE, MIMETYPE, FILENAME, LAST_UPDATE, ID)
 Values
   ('IPI-000001', 'MD. JASIM UDDIN FCA', 'Accounts', 'Pharma', 'IPI-009129', 
    TO_DATE('9/1/2025', 'MM/DD/YYYY'), '5', NULL, NULL, 5);
Insert into DEPAT_HEAD
   (EMPCODE, E_NAME, DEPT_NAME, UNIT, CREATE_BY, 
    CREATE_DATE, MIMETYPE, FILENAME, LAST_UPDATE, ID)
 Values
   ('IPI-003357', 'MD. HAFIZUR RAHMAN', 'Product Development', 'Pharma', 'IPI-009129', 
    TO_DATE('9/1/2025', 'MM/DD/YYYY'), '8', NULL, NULL, 8);
Insert into DEPAT_HEAD
   (EMPCODE, E_NAME, DEPT_NAME, UNIT, CREATE_BY, 
    CREATE_DATE, MIMETYPE, FILENAME, LAST_UPDATE, ID)
 Values
   ('IPI-004302', 'MD. MOSTAFIJUR RAHMAN', 'Accounts', 'Pharma', 'IPI-009129', 
    TO_DATE('9/1/2025', 'MM/DD/YYYY'), '10', NULL, NULL, 11);
Insert into DEPAT_HEAD
   (EMPCODE, E_NAME, DEPT_NAME, UNIT, CREATE_BY, 
    CREATE_DATE, MIMETYPE, FILENAME, LAST_UPDATE, ID)
 Values
   ('IPI-000001', 'MD. JASIM UDDIN FCA', 'Accounts', 'Pharma', 'IPI-009129', 
    TO_DATE('9/9/2025', 'MM/DD/YYYY'), NULL, NULL, NULL, 15);
Insert into DEPAT_HEAD
   (EMPCODE, E_NAME, DEPT_NAME, UNIT, CREATE_BY, 
    CREATE_DATE, MIMETYPE, FILENAME, LAST_UPDATE, ID)
 Values
   ('INM-000002', 'MD. ABUL KALAM', 'Quality Assurance', 'Herbal', 'IPI-009129', 
    TO_DATE('9/1/2025', 'MM/DD/YYYY'), '10', NULL, NULL, 12);
Insert into DEPAT_HEAD
   (EMPCODE, E_NAME, DEPT_NAME, UNIT, CREATE_BY, 
    CREATE_DATE, MIMETYPE, FILENAME, LAST_UPDATE, ID)
 Values
   ('IPI-002760', 'KHONDOKER ZAKIR HOSSAIN', 'Information Technology', 'Pharma', 'IPI-009129', 
    TO_DATE('9/1/2025', 'MM/DD/YYYY'), '1', NULL, NULL, 1);
Insert into DEPAT_HEAD
   (EMPCODE, E_NAME, DEPT_NAME, UNIT, CREATE_BY, 
    CREATE_DATE, MIMETYPE, FILENAME, LAST_UPDATE, ID)
 Values
   ('IPI-000831', 'S.M. LUTFUL BARI', 'Purchase', 'Pharma', 'IPI-009129', 
    TO_DATE('9/1/2025', 'MM/DD/YYYY'), '2', NULL, NULL, 2);
Insert into DEPAT_HEAD
   (EMPCODE, E_NAME, DEPT_NAME, UNIT, CREATE_BY, 
    CREATE_DATE, MIMETYPE, FILENAME, LAST_UPDATE, ID)
 Values
   ('IPI-000212', 'MD. SALIM MOLLA', 'Distribution', 'Pharma', 'IPI-009129', 
    TO_DATE('9/1/2025', 'MM/DD/YYYY'), '6', NULL, NULL, 6);
Insert into DEPAT_HEAD
   (EMPCODE, E_NAME, DEPT_NAME, UNIT, CREATE_BY, 
    CREATE_DATE, MIMETYPE, FILENAME, LAST_UPDATE, ID)
 Values
   ('IPI-000814', 'MAHMUD NUR  SOBUZ', 'Human Resource', 'Pharma', 'IPI-009129', 
    TO_DATE('9/9/2025', 'MM/DD/YYYY'), NULL, NULL, NULL, 14);
Insert into DEPAT_HEAD
   (EMPCODE, E_NAME, DEPT_NAME, UNIT, CREATE_BY, 
    CREATE_DATE, MIMETYPE, FILENAME, LAST_UPDATE, ID)
 Values
   ('IPI-008316', 'MD. SHABDAR HOSSAIN', 'Engineering', 'Pharma', 'IPI-009129', 
    TO_DATE('9/1/2025', 'MM/DD/YYYY'), '7', NULL, NULL, 7);
Insert into DEPAT_HEAD
   (EMPCODE, E_NAME, DEPT_NAME, UNIT, CREATE_BY, 
    CREATE_DATE, MIMETYPE, FILENAME, LAST_UPDATE, ID)
 Values
   ('IPI-001360', 'MD. PARVEZ KABIR', 'Marketing', 'Pharma', 'IPI-009129', 
    TO_DATE('9/1/2025', 'MM/DD/YYYY'), '9', NULL, NULL, 9);
Insert into DEPAT_HEAD
   (EMPCODE, E_NAME, DEPT_NAME, UNIT, CREATE_BY, 
    CREATE_DATE, MIMETYPE, FILENAME, LAST_UPDATE, ID)
 Values
   ('IPI-000827', 'SAYED AMIMUL IHSAN', 'Administration', 'Pharma', 'IPI-009129', 
    TO_DATE('9/9/2025', 'MM/DD/YYYY'), NULL, NULL, NULL, 13);
Insert into DEPAT_HEAD
   (EMPCODE, E_NAME, DEPT_NAME, UNIT, CREATE_BY, 
    CREATE_DATE, MIMETYPE, FILENAME, LAST_UPDATE, ID)
 Values
   ('IPI-004157', 'DR. SHAH MD. BULBUL ISLAM', 'Sales', 'Pharma', 'IPI-009129', 
    TO_DATE('9/9/2025', 'MM/DD/YYYY'), '10', NULL, NULL, 10);
COMMIT;
