CREATE TABLE DEPAT_HEAD
(
  EMPCODE      VARCHAR2(15 BYTE),
  E_NAME       VARCHAR2(150 BYTE),
  DEPT_NAME    VARCHAR2(100 BYTE),
  UNIT         VARCHAR2(50 BYTE),
  CREATE_BY    VARCHAR2(100 BYTE),
  CREATE_DATE  DATE,
  MIMETYPE     VARCHAR2(250 BYTE),
  FILENAME     VARCHAR2(255 BYTE),
  LAST_UPDATE  DATE,
  IMAGE        BLOB,
  ID           NUMBER
);

ALTER TABLE DBMIS.DEPAT_HEAD ADD (
  CONSTRAINT DEPAT_HEAD_PK
  PRIMARY KEY
  (ID)
  USING INDEX DBMIS.DEPAT_HEAD_PK
  ENABLE VALIDATE);
