CREATE TABLE DF_SEQUENCE  -- Approval Sequence by L1 to L12
(
  SQ_ID        NUMBER(15),
  TYPE_ID      NUMBER(15),
  UNIT_ID      VARCHAR2(15 BYTE),
  DEPT_ID      VARCHAR2(200 BYTE),
  L1_EMPCODE   VARCHAR2(15 BYTE),
  L2_EMPCODE   VARCHAR2(15 BYTE),
  L3_EMPCODE   VARCHAR2(15 BYTE),
  L4_EMPCODE   VARCHAR2(15 BYTE),
  L5_EMPCODE   VARCHAR2(15 BYTE),
  L6_EMPCODE   VARCHAR2(15 BYTE),
  L7_EMPCODE   VARCHAR2(15 BYTE),
  L8_EMPCODE   VARCHAR2(15 BYTE),
  L9_EMPCODE   VARCHAR2(15 BYTE),
  L10_EMPCODE  VARCHAR2(15 BYTE),
  L11_EMPCODE  VARCHAR2(15 BYTE),
  L12_EMPCODE  VARCHAR2(15 BYTE),
  IS_ACTIVE    VARCHAR2(10 BYTE),
  INSERT_BY    VARCHAR2(20 BYTE),
  INSERT_DATE  DATE,
  INSERT_TIME  VARCHAR2(50 BYTE),
  UPDATE_BY    VARCHAR2(20 BYTE),
  UPDATE_DATE  DATE,
  UPDATE_TIME  VARCHAR2(50 BYTE),
  ITEM_ID      NUMBER,
  CATEGORY_ID  NUMBER,
  ENT_BY       VARCHAR2(30 BYTE),
  ENT_DATE     DATE,
  UPD_BY       VARCHAR2(30 BYTE),
  UPD_DATE     DATE,
  COMPANY      VARCHAR2(100 BYTE),
  LOCATION     VARCHAR2(30 BYTE),
  ITEM_AMT     NUMBER
);


ALTER TABLE DBMIS.DF_SEQUENCE ADD (
  CONSTRAINT UK_SEQ
  UNIQUE (TYPE_ID, UNIT_ID, CATEGORY_ID, DEPT_ID, ITEM_ID, LOCATION, COMPANY, ITEM_AMT)
  );


SET DEFINE OFF;
Insert into DF_SEQUENCE
   (SQ_ID, TYPE_ID, UNIT_ID, DEPT_ID, L1_EMPCODE, 
    L2_EMPCODE, L3_EMPCODE, L4_EMPCODE, L5_EMPCODE, L6_EMPCODE, 
    L7_EMPCODE, L8_EMPCODE, L9_EMPCODE, L10_EMPCODE, L11_EMPCODE, 
    L12_EMPCODE, IS_ACTIVE, INSERT_BY, INSERT_DATE, INSERT_TIME, 
    UPDATE_BY, UPDATE_DATE, UPDATE_TIME, ITEM_ID, CATEGORY_ID, 
    ENT_BY, ENT_DATE, UPD_BY, UPD_DATE, COMPANY, 
    LOCATION, ITEM_AMT)
 Values
   (1, 5, 'Unit-01', NULL, 'IPI-000814', 
    'IPI-007377', 'IPI-007378', 'IPI-000789', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'Y', 'IPI-009129', TO_DATE('9/1/2025', 'MM/DD/YYYY'), '01-SEP-25', 
    'IPI-009129', TO_DATE('9/1/2025', 'MM/DD/YYYY'), '01-SEP-25', NULL, 1, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into DF_SEQUENCE
   (SQ_ID, TYPE_ID, UNIT_ID, DEPT_ID, L1_EMPCODE, 
    L2_EMPCODE, L3_EMPCODE, L4_EMPCODE, L5_EMPCODE, L6_EMPCODE, 
    L7_EMPCODE, L8_EMPCODE, L9_EMPCODE, L10_EMPCODE, L11_EMPCODE, 
    L12_EMPCODE, IS_ACTIVE, INSERT_BY, INSERT_DATE, INSERT_TIME, 
    UPDATE_BY, UPDATE_DATE, UPDATE_TIME, ITEM_ID, CATEGORY_ID, 
    ENT_BY, ENT_DATE, UPD_BY, UPD_DATE, COMPANY, 
    LOCATION, ITEM_AMT)
 Values
   (4, 7, 'Unit-01', NULL, 'IPI-002760', 
    'IPI-007377', 'IPI-000789', NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', 'IPI-009129', TO_DATE('9/9/2025', 'MM/DD/YYYY'), '09-SEP-25', 
    'IPI-009129', TO_DATE('9/9/2025', 'MM/DD/YYYY'), '09-SEP-25', 24, 3, 
    NULL, NULL, NULL, NULL, 'IPI', 
    'FAC', 75000);
Insert into DF_SEQUENCE
   (SQ_ID, TYPE_ID, UNIT_ID, DEPT_ID, L1_EMPCODE, 
    L2_EMPCODE, L3_EMPCODE, L4_EMPCODE, L5_EMPCODE, L6_EMPCODE, 
    L7_EMPCODE, L8_EMPCODE, L9_EMPCODE, L10_EMPCODE, L11_EMPCODE, 
    L12_EMPCODE, IS_ACTIVE, INSERT_BY, INSERT_DATE, INSERT_TIME, 
    UPDATE_BY, UPDATE_DATE, UPDATE_TIME, ITEM_ID, CATEGORY_ID, 
    ENT_BY, ENT_DATE, UPD_BY, UPD_DATE, COMPANY, 
    LOCATION, ITEM_AMT)
 Values
   (5, 7, 'Unit-01', NULL, 'IPI-008316', 
    'IPI-000538', 'IPI-000001', 'IPI-007377', 'IPI-007378', 'IPI-000790', 
    'IPI-000789', NULL, NULL, NULL, NULL, 
    NULL, 'Y', 'IPI-009129', TO_DATE('9/9/2025', 'MM/DD/YYYY'), '09-SEP-25', 
    'IPI-009129', TO_DATE('9/9/2025', 'MM/DD/YYYY'), '09-SEP-25', 7, 3, 
    NULL, NULL, NULL, NULL, 'IPI', 
    'FAC', 500000);
Insert into DF_SEQUENCE
   (SQ_ID, TYPE_ID, UNIT_ID, DEPT_ID, L1_EMPCODE, 
    L2_EMPCODE, L3_EMPCODE, L4_EMPCODE, L5_EMPCODE, L6_EMPCODE, 
    L7_EMPCODE, L8_EMPCODE, L9_EMPCODE, L10_EMPCODE, L11_EMPCODE, 
    L12_EMPCODE, IS_ACTIVE, INSERT_BY, INSERT_DATE, INSERT_TIME, 
    UPDATE_BY, UPDATE_DATE, UPDATE_TIME, ITEM_ID, CATEGORY_ID, 
    ENT_BY, ENT_DATE, UPD_BY, UPD_DATE, COMPANY, 
    LOCATION, ITEM_AMT)
 Values
   (3, 7, 'Unit-01', NULL, 'IPI-002760', 
    'IPI-000831', 'IPI-007377', 'IPI-007378', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'Y', 'IPI-009129', TO_DATE('9/8/2025', 'MM/DD/YYYY'), '08-SEP-25', 
    'IPI-009129', TO_DATE('9/8/2025', 'MM/DD/YYYY'), '08-SEP-25', 24, 3, 
    NULL, NULL, NULL, NULL, 'IPI', 
    'HDO', NULL);
COMMIT;
