CREATE TABLE JOB_GRADES
(
    ID             NUMBER PRIMARY KEY,
    GRADE_NAME     VARCHAR2 (100 BYTE),
    MIN_SALARY     NUMBER,
    MAX_SALARY     NUMBER,
    DESCRIPTION    VARCHAR2 (255 BYTE),
    ENT_DATE       DATE DEFAULT SYSDATE,
    UPD_DATE       DATE,
    ENT_BY         NUMBER,             --REF Employee ID as employees table id
    UPD_BY         NUMBER,
    SCALES         VARCHAR2 (100 BYTE),
    GRADE_CODE     VARCHAR2 (30 BYTE),
    GRADE_ORDER    NUMBER (3)
);
SET DEFINE OFF;
Insert into JOB_GRADES
   (ID, GRADE_NAME, MIN_SALARY, MAX_SALARY, DESCRIPTION, 
    ENT_DATE, UPD_DATE, ENT_BY, UPD_BY, SCALES, 
    GRADE_CODE, GRADE_ORDER)
 Values
   (5, 'GRADE-05', NULL, NULL, NULL, 
    TO_DATE('10/2/2024', 'MM/DD/YYYY'), NULL, 555009129, NULL, NULL, 
    'GRADE-05', 5);
Insert into JOB_GRADES
   (ID, GRADE_NAME, MIN_SALARY, MAX_SALARY, DESCRIPTION, 
    ENT_DATE, UPD_DATE, ENT_BY, UPD_BY, SCALES, 
    GRADE_CODE, GRADE_ORDER)
 Values
   (3, 'GRADE-03', NULL, NULL, NULL, 
    TO_DATE('10/2/2024', 'MM/DD/YYYY'), NULL, 555009129, NULL, NULL, 
    'GRADE-03', 3);
Insert into JOB_GRADES
   (ID, GRADE_NAME, MIN_SALARY, MAX_SALARY, DESCRIPTION, 
    ENT_DATE, UPD_DATE, ENT_BY, UPD_BY, SCALES, 
    GRADE_CODE, GRADE_ORDER)
 Values
   (4, 'GRADE-04', NULL, NULL, NULL, 
    TO_DATE('10/2/2024', 'MM/DD/YYYY'), NULL, 555009129, NULL, NULL, 
    'GRADE-04', 4);
Insert into JOB_GRADES
   (ID, GRADE_NAME, MIN_SALARY, MAX_SALARY, DESCRIPTION, 
    ENT_DATE, UPD_DATE, ENT_BY, UPD_BY, SCALES, 
    GRADE_CODE, GRADE_ORDER)
 Values
   (1, 'GRADE-01', NULL, NULL, NULL, 
    TO_DATE('10/2/2024', 'MM/DD/YYYY'), NULL, 555009129, NULL, NULL, 
    'GRADE-01', 1);
Insert into JOB_GRADES
   (ID, GRADE_NAME, MIN_SALARY, MAX_SALARY, DESCRIPTION, 
    ENT_DATE, UPD_DATE, ENT_BY, UPD_BY, SCALES, 
    GRADE_CODE, GRADE_ORDER)
 Values
   (2, 'GRADE-02', NULL, NULL, NULL, 
    TO_DATE('10/2/2024', 'MM/DD/YYYY'), NULL, 555009129, NULL, NULL, 
    'GRADE-02', 2);
COMMIT;


CREATE TABLE ALLOWANCE_HEAD
(
    HEAD_ID         NUMBER,
    HEAD_CODE       VARCHAR2 (20 BYTE) NOT NULL,
    HEAD_NAME       VARCHAR2 (100 BYTE) NOT NULL,
    HEAD_TYPE       VARCHAR2 (10 BYTE) NOT NULL,
    CALC_TYPE       VARCHAR2 (10 BYTE) NOT NULL,
    IS_TAXABLE      VARCHAR2 (1 BYTE) DEFAULT 'Y',
    PRINT_ORDER     NUMBER (3),
    IS_ACTIVE       VARCHAR2 (1 BYTE) DEFAULT 'Y',
    REMARKS         VARCHAR2 (200 BYTE),
    CREATED_BY      NUMBER,
    CREATED_DATE    DATE DEFAULT SYSDATE,
    UPDATED_BY      NUMBER,
    UPDATED_DATE    DATE
);
SET DEFINE OFF;
Insert into ALLOWANCE_HEAD
   (HEAD_ID, HEAD_CODE, HEAD_NAME, HEAD_TYPE, CALC_TYPE, 
    IS_TAXABLE, PRINT_ORDER, IS_ACTIVE, REMARKS, CREATED_BY, 
    CREATED_DATE, UPDATED_BY, UPDATED_DATE, IS_ADV)
 Values
   (1, '001', 'Basic Salary', 'EARNING', 'FIXED', 
    'Y', 1, 'Y', NULL, NULL, 
    TO_DATE('4/6/2026 7:15:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, 'N');
Insert into ALLOWANCE_HEAD
   (HEAD_ID, HEAD_CODE, HEAD_NAME, HEAD_TYPE, CALC_TYPE, 
    IS_TAXABLE, PRINT_ORDER, IS_ACTIVE, REMARKS, CREATED_BY, 
    CREATED_DATE, UPDATED_BY, UPDATED_DATE, IS_ADV)
 Values
   (5, '005', 'House Rent', 'EARNING', 'PERCENT', 
    'Y', 5, 'Y', NULL, NULL, 
    TO_DATE('4/6/2026 7:15:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, 'N');
Insert into ALLOWANCE_HEAD
   (HEAD_ID, HEAD_CODE, HEAD_NAME, HEAD_TYPE, CALC_TYPE, 
    IS_TAXABLE, PRINT_ORDER, IS_ACTIVE, REMARKS, CREATED_BY, 
    CREATED_DATE, UPDATED_BY, UPDATED_DATE, IS_ADV)
 Values
   (7, '007', 'Conveyance  Allow', 'EARNING', 'FIXED', 
    'Y', 7, 'Y', NULL, NULL, 
    TO_DATE('4/6/2026 7:15:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, 'N');
Insert into ALLOWANCE_HEAD
   (HEAD_ID, HEAD_CODE, HEAD_NAME, HEAD_TYPE, CALC_TYPE, 
    IS_TAXABLE, PRINT_ORDER, IS_ACTIVE, REMARKS, CREATED_BY, 
    CREATED_DATE, UPDATED_BY, UPDATED_DATE, IS_ADV)
 Values
   (10, '010', 'Medical Allowance', 'EARNING', 'FIXED', 
    'Y', 10, 'Y', NULL, NULL, 
    TO_DATE('4/6/2026 7:15:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, 'N');
Insert into ALLOWANCE_HEAD
   (HEAD_ID, HEAD_CODE, HEAD_NAME, HEAD_TYPE, CALC_TYPE, 
    IS_TAXABLE, PRINT_ORDER, IS_ACTIVE, REMARKS, CREATED_BY, 
    CREATED_DATE, UPDATED_BY, UPDATED_DATE, IS_ADV)
 Values
   (55, '055', 'Income Tax', 'DEDUCTION', 'FIXED', 
    'Y', 55, 'Y', NULL, NULL, 
    TO_DATE('4/6/2026 7:16:48 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, 'N');
Insert into ALLOWANCE_HEAD
   (HEAD_ID, HEAD_CODE, HEAD_NAME, HEAD_TYPE, CALC_TYPE, 
    IS_TAXABLE, PRINT_ORDER, IS_ACTIVE, REMARKS, CREATED_BY, 
    CREATED_DATE, UPDATED_BY, UPDATED_DATE, IS_ADV)
 Values
   (57, '057', 'P.F. Contribution', 'DEDUCTION', 'PERCENT', 
    'Y', 57, 'Y', NULL, NULL, 
    TO_DATE('4/6/2026 7:16:48 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, 'N');
COMMIT;


CREATE TABLE HRMS.PAY_SCALE_MASTER
(
  SCALE_ID         NUMBER,
  GRADE_ID         NUMBER                       NOT NULL,
  REVISION_NO      NUMBER(3)                    DEFAULT 1,
  REVISION_NAME    VARCHAR2(100 BYTE),
  START_BASIC      NUMBER(10,2)                 NOT NULL,
  INCREMENT_1      NUMBER(10,2)                 NOT NULL,
  STEPS_BEFORE_EB  NUMBER(3)                    DEFAULT 10                    NOT NULL,
  EB_BASIC         NUMBER(10,2)                 NOT NULL,
  INCREMENT_2      NUMBER(10,2)                 NOT NULL,
  STEPS_AFTER_EB   NUMBER(3)                    DEFAULT 15                    NOT NULL,
  MAX_BASIC        NUMBER(10,2)                 NOT NULL,
  IS_ACTIVE        VARCHAR2(1 BYTE)             DEFAULT 'Y'                   NOT NULL,
  EFFECTIVE_FROM   DATE,
  EFFECTIVE_TO     DATE,
  APPROVED_BY      NUMBER,
  APPROVED_DATE    DATE,
  CREATED_BY       NUMBER,
  CREATED_DATE     DATE                         DEFAULT SYSDATE,
  UPDATED_BY       NUMBER,
  UPDATED_DATE     DATE,
  HR               NUMBER,
  CPF              NUMBER,
  PFCONT           NUMBER,
  CONV             NUMBER,
  MEDICAL          NUMBER,
  ALLOWANCE        NUMBER,
  SAF              NUMBER
);
SET DEFINE OFF;
Insert into PAY_SCALE_MASTER
   (SCALE_ID, GRADE_ID, REVISION_NO, REVISION_NAME, START_BASIC, 
    INCREMENT_1, STEPS_BEFORE_EB, EB_BASIC, INCREMENT_2, STEPS_AFTER_EB, 
    MAX_BASIC, IS_ACTIVE, EFFECTIVE_FROM, EFFECTIVE_TO, APPROVED_BY, 
    APPROVED_DATE, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, 
    HR, CPF, PFCONT, CONV, MEDICAL, 
    ALLOWANCE, SAF)
 Values
   (1, 1, 1, 'Pay Scale 2025', 46550, 
    4190, 10, 88450, 4310, 15, 
    153100, 'Y', TO_DATE('7/1/2025', 'MM/DD/YYYY'), NULL, NULL, 
    TO_DATE('3/31/2026', 'MM/DD/YYYY'), NULL, TO_DATE('3/31/2026', 'MM/DD/YYYY'), NULL, NULL, 
    75, 10, 20, 6500, 8000, 
    17000, 800);
Insert into PAY_SCALE_MASTER
   (SCALE_ID, GRADE_ID, REVISION_NO, REVISION_NAME, START_BASIC, 
    INCREMENT_1, STEPS_BEFORE_EB, EB_BASIC, INCREMENT_2, STEPS_AFTER_EB, 
    MAX_BASIC, IS_ACTIVE, EFFECTIVE_FROM, EFFECTIVE_TO, APPROVED_BY, 
    APPROVED_DATE, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, 
    HR, CPF, PFCONT, CONV, MEDICAL, 
    ALLOWANCE, SAF)
 Values
   (2, 2, 1, 'Pay Scale 2025', 37050, 
    3330, 10, 70350, 3430, 15, 
    121800, 'Y', TO_DATE('7/1/2025', 'MM/DD/YYYY'), NULL, NULL, 
    TO_DATE('3/31/2026 10:33:05 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, TO_DATE('3/31/2026 10:33:05 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, 
    75, 10, 20, 6500, 8000, 
    14000, 800);
Insert into PAY_SCALE_MASTER
   (SCALE_ID, GRADE_ID, REVISION_NO, REVISION_NAME, START_BASIC, 
    INCREMENT_1, STEPS_BEFORE_EB, EB_BASIC, INCREMENT_2, STEPS_AFTER_EB, 
    MAX_BASIC, IS_ACTIVE, EFFECTIVE_FROM, EFFECTIVE_TO, APPROVED_BY, 
    APPROVED_DATE, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, 
    HR, CPF, PFCONT, CONV, MEDICAL, 
    ALLOWANCE, SAF)
 Values
   (3, 3, 1, 'Pay Scale 2025', 30550, 
    2750, 10, 58050, 2830, 15, 
    100500, 'Y', TO_DATE('7/1/2025', 'MM/DD/YYYY'), NULL, NULL, 
    TO_DATE('3/31/2026 10:33:05 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, TO_DATE('3/31/2026 10:33:05 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, 
    75, 10, 20, 5500, 7500, 
    10000, 800);
Insert into PAY_SCALE_MASTER
   (SCALE_ID, GRADE_ID, REVISION_NO, REVISION_NAME, START_BASIC, 
    INCREMENT_1, STEPS_BEFORE_EB, EB_BASIC, INCREMENT_2, STEPS_AFTER_EB, 
    MAX_BASIC, IS_ACTIVE, EFFECTIVE_FROM, EFFECTIVE_TO, APPROVED_BY, 
    APPROVED_DATE, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, 
    HR, CPF, PFCONT, CONV, MEDICAL, 
    ALLOWANCE, SAF)
 Values
   (4, 4, 1, 'Pay Scale 2025', 25050, 
    2250, 10, 47550, 2320, 15, 
    82350, 'Y', TO_DATE('7/1/2025', 'MM/DD/YYYY'), NULL, NULL, 
    TO_DATE('3/31/2026', 'MM/DD/YYYY'), NULL, TO_DATE('3/31/2026', 'MM/DD/YYYY'), NULL, NULL, 
    75, 10, 20, 5000, 6000, 
    9000, 800);
Insert into PAY_SCALE_MASTER
   (SCALE_ID, GRADE_ID, REVISION_NO, REVISION_NAME, START_BASIC, 
    INCREMENT_1, STEPS_BEFORE_EB, EB_BASIC, INCREMENT_2, STEPS_AFTER_EB, 
    MAX_BASIC, IS_ACTIVE, EFFECTIVE_FROM, EFFECTIVE_TO, APPROVED_BY, 
    APPROVED_DATE, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, 
    HR, CPF, PFCONT, CONV, MEDICAL, 
    ALLOWANCE, SAF)
 Values
   (5, 5, 1, 'Pay Scale 2025', 22050, 
    1980, 10, 41850, 2040, 15, 
    72450, 'Y', TO_DATE('7/1/2025', 'MM/DD/YYYY'), NULL, NULL, 
    TO_DATE('3/31/2026', 'MM/DD/YYYY'), NULL, TO_DATE('3/31/2026', 'MM/DD/YYYY'), NULL, NULL, 
    75, 10, 20, 5000, 5500, 
    7500, 800);
Insert into PAY_SCALE_MASTER
   (SCALE_ID, GRADE_ID, REVISION_NO, REVISION_NAME, START_BASIC, 
    INCREMENT_1, STEPS_BEFORE_EB, EB_BASIC, INCREMENT_2, STEPS_AFTER_EB, 
    MAX_BASIC, IS_ACTIVE, EFFECTIVE_FROM, EFFECTIVE_TO, APPROVED_BY, 
    APPROVED_DATE, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, 
    HR, CPF, PFCONT, CONV, MEDICAL, 
    ALLOWANCE, SAF)
 Values
   (6, 6, 1, 'Pay Scale 2025', 19050, 
    1710, 10, 36150, 1760, 15, 
    62550, 'Y', TO_DATE('7/1/2025', 'MM/DD/YYYY'), NULL, NULL, 
    TO_DATE('3/31/2026', 'MM/DD/YYYY'), NULL, TO_DATE('3/31/2026', 'MM/DD/YYYY'), NULL, NULL, 
    75, 10, 20, 3500, 4500, 
    7000, 400);
Insert into PAY_SCALE_MASTER
   (SCALE_ID, GRADE_ID, REVISION_NO, REVISION_NAME, START_BASIC, 
    INCREMENT_1, STEPS_BEFORE_EB, EB_BASIC, INCREMENT_2, STEPS_AFTER_EB, 
    MAX_BASIC, IS_ACTIVE, EFFECTIVE_FROM, EFFECTIVE_TO, APPROVED_BY, 
    APPROVED_DATE, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, 
    HR, CPF, PFCONT, CONV, MEDICAL, 
    ALLOWANCE, SAF)
 Values
   (7, 7, 1, 'Pay Scale 2025', 17050, 
    1530, 10, 32350, 1580, 15, 
    56050, 'Y', TO_DATE('7/1/2025', 'MM/DD/YYYY'), NULL, NULL, 
    TO_DATE('3/31/2026', 'MM/DD/YYYY'), NULL, TO_DATE('3/31/2026', 'MM/DD/YYYY'), NULL, NULL, 
    75, 10, 20, 2800, 4000, 
    6500, 400);
Insert into PAY_SCALE_MASTER
   (SCALE_ID, GRADE_ID, REVISION_NO, REVISION_NAME, START_BASIC, 
    INCREMENT_1, STEPS_BEFORE_EB, EB_BASIC, INCREMENT_2, STEPS_AFTER_EB, 
    MAX_BASIC, IS_ACTIVE, EFFECTIVE_FROM, EFFECTIVE_TO, APPROVED_BY, 
    APPROVED_DATE, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, 
    HR, CPF, PFCONT, CONV, MEDICAL, 
    ALLOWANCE, SAF)
 Values
   (8, 8, 1, 'Pay Scale 2025', 15250, 
    1370, 10, 28950, 1410, 15, 
    50100, 'Y', TO_DATE('7/1/2025', 'MM/DD/YYYY'), NULL, NULL, 
    TO_DATE('3/31/2026', 'MM/DD/YYYY'), NULL, TO_DATE('3/31/2026', 'MM/DD/YYYY'), NULL, NULL, 
    75, 10, 20, 2800, 3750, 
    6250, 400);
Insert into PAY_SCALE_MASTER
   (SCALE_ID, GRADE_ID, REVISION_NO, REVISION_NAME, START_BASIC, 
    INCREMENT_1, STEPS_BEFORE_EB, EB_BASIC, INCREMENT_2, STEPS_AFTER_EB, 
    MAX_BASIC, IS_ACTIVE, EFFECTIVE_FROM, EFFECTIVE_TO, APPROVED_BY, 
    APPROVED_DATE, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, 
    HR, CPF, PFCONT, CONV, MEDICAL, 
    ALLOWANCE, SAF)
 Values
   (9, 9, 1, 'Pay Scale 2025', 13300, 
    1200, 10, 25300, 1230, 15, 
    43750, 'Y', TO_DATE('7/1/2025', 'MM/DD/YYYY'), NULL, NULL, 
    TO_DATE('3/31/2026', 'MM/DD/YYYY'), NULL, TO_DATE('3/31/2026', 'MM/DD/YYYY'), NULL, NULL, 
    75, 10, 20, 2500, 3250, 
    5800, 400);
Insert into PAY_SCALE_MASTER
   (SCALE_ID, GRADE_ID, REVISION_NO, REVISION_NAME, START_BASIC, 
    INCREMENT_1, STEPS_BEFORE_EB, EB_BASIC, INCREMENT_2, STEPS_AFTER_EB, 
    MAX_BASIC, IS_ACTIVE, EFFECTIVE_FROM, EFFECTIVE_TO, APPROVED_BY, 
    APPROVED_DATE, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, 
    HR, CPF, PFCONT, CONV, MEDICAL, 
    ALLOWANCE, SAF)
 Values
   (10, 10, 1, 'Pay Scale 2025', 12250, 
    1100, 10, 23250, 1130, 15, 
    40200, 'Y', TO_DATE('7/1/2025', 'MM/DD/YYYY'), NULL, NULL, 
    TO_DATE('3/31/2026', 'MM/DD/YYYY'), NULL, TO_DATE('3/31/2026', 'MM/DD/YYYY'), NULL, NULL, 
    75, 10, 20, 2500, 2750, 
    4750, 400);
Insert into PAY_SCALE_MASTER
   (SCALE_ID, GRADE_ID, REVISION_NO, REVISION_NAME, START_BASIC, 
    INCREMENT_1, STEPS_BEFORE_EB, EB_BASIC, INCREMENT_2, STEPS_AFTER_EB, 
    MAX_BASIC, IS_ACTIVE, EFFECTIVE_FROM, EFFECTIVE_TO, APPROVED_BY, 
    APPROVED_DATE, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, 
    HR, CPF, PFCONT, CONV, MEDICAL, 
    ALLOWANCE, SAF)
 Values
   (11, 11, 1, 'Pay Scale 2025', 11000, 
    990, 10, 20900, 1020, 15, 
    36200, 'Y', TO_DATE('7/1/2025', 'MM/DD/YYYY'), NULL, NULL, 
    TO_DATE('3/31/2026', 'MM/DD/YYYY'), NULL, TO_DATE('3/31/2026', 'MM/DD/YYYY'), NULL, NULL, 
    75, 10, 20, 2500, 2450, 
    4000, 200);
Insert into PAY_SCALE_MASTER
   (SCALE_ID, GRADE_ID, REVISION_NO, REVISION_NAME, START_BASIC, 
    INCREMENT_1, STEPS_BEFORE_EB, EB_BASIC, INCREMENT_2, STEPS_AFTER_EB, 
    MAX_BASIC, IS_ACTIVE, EFFECTIVE_FROM, EFFECTIVE_TO, APPROVED_BY, 
    APPROVED_DATE, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, 
    HR, CPF, PFCONT, CONV, MEDICAL, 
    ALLOWANCE, SAF)
 Values
   (12, 12, 1, 'Pay Scale 2025', 10250, 
    920, 10, 19450, 950, 15, 
    33700, 'Y', TO_DATE('7/1/2025', 'MM/DD/YYYY'), NULL, NULL, 
    TO_DATE('3/31/2026', 'MM/DD/YYYY'), NULL, TO_DATE('3/31/2026', 'MM/DD/YYYY'), NULL, NULL, 
    75, 10, 20, 2300, 2450, 
    4000, 200);
Insert into PAY_SCALE_MASTER
   (SCALE_ID, GRADE_ID, REVISION_NO, REVISION_NAME, START_BASIC, 
    INCREMENT_1, STEPS_BEFORE_EB, EB_BASIC, INCREMENT_2, STEPS_AFTER_EB, 
    MAX_BASIC, IS_ACTIVE, EFFECTIVE_FROM, EFFECTIVE_TO, APPROVED_BY, 
    APPROVED_DATE, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, 
    HR, CPF, PFCONT, CONV, MEDICAL, 
    ALLOWANCE, SAF)
 Values
   (13, 13, 1, 'Pay Scale 2025', 9700, 
    870, 10, 18400, 900, 15, 
    31900, 'Y', TO_DATE('7/1/2025', 'MM/DD/YYYY'), NULL, NULL, 
    TO_DATE('3/31/2026', 'MM/DD/YYYY'), NULL, TO_DATE('3/31/2026', 'MM/DD/YYYY'), NULL, NULL, 
    75, 10, 20, 2300, 2300, 
    4000, 200);
Insert into PAY_SCALE_MASTER
   (SCALE_ID, GRADE_ID, REVISION_NO, REVISION_NAME, START_BASIC, 
    INCREMENT_1, STEPS_BEFORE_EB, EB_BASIC, INCREMENT_2, STEPS_AFTER_EB, 
    MAX_BASIC, IS_ACTIVE, EFFECTIVE_FROM, EFFECTIVE_TO, APPROVED_BY, 
    APPROVED_DATE, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, 
    HR, CPF, PFCONT, CONV, MEDICAL, 
    ALLOWANCE, SAF)
 Values
   (14, 14, 1, 'Pay Scale 2025', 9100, 
    820, 10, 17300, 840, 15, 
    29900, 'Y', TO_DATE('7/1/2025', 'MM/DD/YYYY'), NULL, NULL, 
    TO_DATE('3/31/2026', 'MM/DD/YYYY'), NULL, TO_DATE('3/31/2026', 'MM/DD/YYYY'), NULL, NULL, 
    75, 10, 20, 2200, 2200, 
    3100, 200);
Insert into PAY_SCALE_MASTER
   (SCALE_ID, GRADE_ID, REVISION_NO, REVISION_NAME, START_BASIC, 
    INCREMENT_1, STEPS_BEFORE_EB, EB_BASIC, INCREMENT_2, STEPS_AFTER_EB, 
    MAX_BASIC, IS_ACTIVE, EFFECTIVE_FROM, EFFECTIVE_TO, APPROVED_BY, 
    APPROVED_DATE, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, 
    HR, CPF, PFCONT, CONV, MEDICAL, 
    ALLOWANCE, SAF)
 Values
   (15, 15, 1, 'Pay Scale 2025', 8250, 
    740, 10, 15650, 765, 15, 
    27125, 'Y', TO_DATE('7/1/2025', 'MM/DD/YYYY'), NULL, NULL, 
    TO_DATE('3/31/2026', 'MM/DD/YYYY'), NULL, TO_DATE('3/31/2026', 'MM/DD/YYYY'), NULL, NULL, 
    75, 10, 20, 2000, 2000, 
    2325, 200);
Insert into PAY_SCALE_MASTER
   (SCALE_ID, GRADE_ID, REVISION_NO, REVISION_NAME, START_BASIC, 
    INCREMENT_1, STEPS_BEFORE_EB, EB_BASIC, INCREMENT_2, STEPS_AFTER_EB, 
    MAX_BASIC, IS_ACTIVE, EFFECTIVE_FROM, EFFECTIVE_TO, APPROVED_BY, 
    APPROVED_DATE, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, 
    HR, CPF, PFCONT, CONV, MEDICAL, 
    ALLOWANCE, SAF)
 Values
   (16, 16, 1, 'Pay Scale 2025', 7700, 
    695, 10, 14650, 710, 15, 
    25300, 'Y', TO_DATE('7/1/2025', 'MM/DD/YYYY'), NULL, NULL, 
    TO_DATE('3/31/2026 10:33:05 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, TO_DATE('3/31/2026 10:33:05 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, 
    75, 10, 20, 2000, 2000, 
    2325, 100);
Insert into PAY_SCALE_MASTER
   (SCALE_ID, GRADE_ID, REVISION_NO, REVISION_NAME, START_BASIC, 
    INCREMENT_1, STEPS_BEFORE_EB, EB_BASIC, INCREMENT_2, STEPS_AFTER_EB, 
    MAX_BASIC, IS_ACTIVE, EFFECTIVE_FROM, EFFECTIVE_TO, APPROVED_BY, 
    APPROVED_DATE, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, 
    HR, CPF, PFCONT, CONV, MEDICAL, 
    ALLOWANCE, SAF)
 Values
   (17, 17, 1, 'Pay Scale 2025', 7150, 
    645, 10, 13600, 660, 15, 
    23500, 'Y', TO_DATE('7/1/2025', 'MM/DD/YYYY'), NULL, NULL, 
    TO_DATE('3/31/2026 10:33:05 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, TO_DATE('3/31/2026 10:33:05 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, 
    75, 10, 20, 2000, 2000, 
    2325, 100);
Insert into PAY_SCALE_MASTER
   (SCALE_ID, GRADE_ID, REVISION_NO, REVISION_NAME, START_BASIC, 
    INCREMENT_1, STEPS_BEFORE_EB, EB_BASIC, INCREMENT_2, STEPS_AFTER_EB, 
    MAX_BASIC, IS_ACTIVE, EFFECTIVE_FROM, EFFECTIVE_TO, APPROVED_BY, 
    APPROVED_DATE, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, 
    HR, CPF, PFCONT, CONV, MEDICAL, 
    ALLOWANCE, SAF)
 Values
   (18, 18, 1, 'Pay Scale 2025', 6600, 
    595, 10, 12550, 610, 15, 
    21700, 'Y', TO_DATE('7/1/2025', 'MM/DD/YYYY'), NULL, NULL, 
    TO_DATE('3/31/2026 10:33:05 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, TO_DATE('3/31/2026 10:33:05 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, 
    75, 10, 20, 2000, 2000, 
    2325, 100);
Insert into PAY_SCALE_MASTER
   (SCALE_ID, GRADE_ID, REVISION_NO, REVISION_NAME, START_BASIC, 
    INCREMENT_1, STEPS_BEFORE_EB, EB_BASIC, INCREMENT_2, STEPS_AFTER_EB, 
    MAX_BASIC, IS_ACTIVE, EFFECTIVE_FROM, EFFECTIVE_TO, APPROVED_BY, 
    APPROVED_DATE, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, 
    HR, CPF, PFCONT, CONV, MEDICAL, 
    ALLOWANCE, SAF)
 Values
   (19, 19, 1, 'Pay Scale 2025', 6050, 
    545, 10, 11500, 560, 15, 
    19900, 'Y', TO_DATE('7/1/2025', 'MM/DD/YYYY'), NULL, NULL, 
    TO_DATE('3/31/2026 10:33:05 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, TO_DATE('3/31/2026 10:33:05 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, 
    75, 10, 20, 2000, 2000, 
    2325, 100);
Insert into PAY_SCALE_MASTER
   (SCALE_ID, GRADE_ID, REVISION_NO, REVISION_NAME, START_BASIC, 
    INCREMENT_1, STEPS_BEFORE_EB, EB_BASIC, INCREMENT_2, STEPS_AFTER_EB, 
    MAX_BASIC, IS_ACTIVE, EFFECTIVE_FROM, EFFECTIVE_TO, APPROVED_BY, 
    APPROVED_DATE, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, 
    HR, CPF, PFCONT, CONV, MEDICAL, 
    ALLOWANCE, SAF)
 Values
   (20, 20, 1, 'Pay Scale 2025', 5500, 
    500, 10, 10500, 510, 15, 
    18150, 'Y', TO_DATE('7/1/2025', 'MM/DD/YYYY'), NULL, NULL, 
    TO_DATE('3/31/2026', 'MM/DD/YYYY'), NULL, TO_DATE('3/31/2026', 'MM/DD/YYYY'), NULL, NULL, 
    75, 10, 20, 2000, 2000, 
    2325, 100);
COMMIT;



CREATE TABLE emp_salary_structure
(
    sals_id          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    employee_id      NUMBER REFERENCES employees (id),
    slno             NUMBER,
    headcode         VARCHAR2 (20),---allowance_head
    amount           NUMBER (12, 2) DEFAULT 0,  
    revision_type    VARCHAR2 (1) DEFAULT 'J' CHECK(revision_type IN ('J','I','P','R')),
    -- J=Joining, I=Increment, P=Promotion, R=Revision Payscale
    is_active        VARCHAR2 (1) DEFAULT 'Y' CHECK (is_active IN ('Y', 'N')),
    created_by       NUMBER,
    created_date     DATE DEFAULT SYSDATE,
    updated_by       NUMBER,
    updated_date     DATE
);

SET DEFINE OFF;
Insert into EMP_SALARY_STRUCTURE
   (SALS_ID, EMPLOYEE_ID, SLNO, HEADCODE, AMOUNT, 
    REVISION_TYPE, IS_ACTIVE, CREATED_BY, CREATED_DATE, UPDATED_BY, 
    UPDATED_DATE)
 Values
   (39582, 555009129, 1, '001', 14500, 
    'J', 'Y', NULL, TO_DATE('4/21/2026', 'MM/DD/YYYY'), NULL, 
    NULL);
Insert into EMP_SALARY_STRUCTURE
   (SALS_ID, EMPLOYEE_ID, SLNO, HEADCODE, AMOUNT, 
    REVISION_TYPE, IS_ACTIVE, CREATED_BY, CREATED_DATE, UPDATED_BY, 
    UPDATED_DATE)
 Values
   (33610, 555009129, 5, '005', 10875, 
    'J', 'Y', NULL, TO_DATE('4/21/2026 12:22:34 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, 
    NULL);
Insert into EMP_SALARY_STRUCTURE
   (SALS_ID, EMPLOYEE_ID, SLNO, HEADCODE, AMOUNT, 
    REVISION_TYPE, IS_ACTIVE, CREATED_BY, CREATED_DATE, UPDATED_BY, 
    UPDATED_DATE)
 Values
   (33611, 555009129, 7, '007', 2500, 
    'J', 'Y', NULL, TO_DATE('4/21/2026', 'MM/DD/YYYY'), NULL, 
    NULL);
Insert into EMP_SALARY_STRUCTURE
   (SALS_ID, EMPLOYEE_ID, SLNO, HEADCODE, AMOUNT, 
    REVISION_TYPE, IS_ACTIVE, CREATED_BY, CREATED_DATE, UPDATED_BY, 
    UPDATED_DATE)
 Values
   (33612, 555009129, 10, '010', 3250, 
    'J', 'Y', NULL, TO_DATE('4/21/2026 12:22:34 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, 
    NULL);
Insert into EMP_SALARY_STRUCTURE
   (SALS_ID, EMPLOYEE_ID, SLNO, HEADCODE, AMOUNT, 
    REVISION_TYPE, IS_ACTIVE, CREATED_BY, CREATED_DATE, UPDATED_BY, 
    UPDATED_DATE)
 Values
   (33613, 555009129, 57, '057', 2900, 
    'J', 'Y', NULL, TO_DATE('4/21/2026 12:22:34 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, 
    NULL);
Insert into EMP_SALARY_STRUCTURE
   (SALS_ID, EMPLOYEE_ID, SLNO, HEADCODE, AMOUNT, 
    REVISION_TYPE, IS_ACTIVE, CREATED_BY, CREATED_DATE, UPDATED_BY, 
    UPDATED_DATE)
 Values
   (33614, 555009129, 13, '013', 1450, 
    'J', 'Y', NULL, TO_DATE('4/21/2026 12:22:34 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, 
    NULL);
Insert into EMP_SALARY_STRUCTURE
   (SALS_ID, EMPLOYEE_ID, SLNO, HEADCODE, AMOUNT, 
    REVISION_TYPE, IS_ACTIVE, CREATED_BY, CREATED_DATE, UPDATED_BY, 
    UPDATED_DATE)
 Values
   (33615, 555009129, 37, '037', 5800, 
    'J', 'Y', NULL, TO_DATE('4/21/2026 12:22:34 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, 
    NULL);
Insert into EMP_SALARY_STRUCTURE
   (SALS_ID, EMPLOYEE_ID, SLNO, HEADCODE, AMOUNT, 
    REVISION_TYPE, IS_ACTIVE, CREATED_BY, CREATED_DATE, UPDATED_BY, 
    UPDATED_DATE)
 Values
   (33616, 555009129, 75, '075', 400, 
    'J', 'Y', NULL, TO_DATE('4/21/2026 12:22:34 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, 
    NULL);
Insert into EMP_SALARY_STRUCTURE
   (SALS_ID, EMPLOYEE_ID, SLNO, HEADCODE, AMOUNT, 
    REVISION_TYPE, IS_ACTIVE, CREATED_BY, CREATED_DATE, UPDATED_BY, 
    UPDATED_DATE)
 Values
   (33617, 555009129, 26, '026', 10000, 
    'J', 'Y', NULL, TO_DATE('4/21/2026 12:22:34 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, 
    NULL);
Insert into EMP_SALARY_STRUCTURE
   (SALS_ID, EMPLOYEE_ID, SLNO, HEADCODE, AMOUNT, 
    REVISION_TYPE, IS_ACTIVE, CREATED_BY, CREATED_DATE, UPDATED_BY, 
    UPDATED_DATE)
 Values
   (49656, 555009129, 55, '055', 500, 
    'J', 'Y', NULL, TO_DATE('4/21/2026 12:22:34 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, 
    NULL);
COMMIT;
