SET DEFINE OFF;
Insert into HR_EMPSALSTRUCTURE
   (SLNO, EMPCODE, YEAROFSTRUC, EDATE, TRNDATE, 
    PARTICULAR, DESIGCODE, AMOUNTPRV, AMOUNTCUR, SALPER, 
    REFNO, YEARMN, PRTCLR_TYPE, PTC_FLAT, HEADCODE, 
    SL, ADDEDBY, ADD_COMP_NAME, ADD_IPADD, ADD_OSUSER, 
    UPD_COMP_NAME, UPD_IPADD, UPD_OSUSER, UPDATEDDATE, UPDATEDBY, 
    SCALE, AMT_B4_F, AMT_AFTER_F, AMT_2B4_F)
 Values
   (121, 'IPI-007001', NULL, NULL, NULL, 
    'Allowance for Special Achievement', NULL, NULL, NULL, 0, 
    '121', NULL, '1', NULL, '121', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL);
Insert into HR_EMPSALSTRUCTURE
   (SLNO, EMPCODE, YEAROFSTRUC, EDATE, TRNDATE, 
    PARTICULAR, DESIGCODE, AMOUNTPRV, AMOUNTCUR, SALPER, 
    REFNO, YEARMN, PRTCLR_TYPE, PTC_FLAT, HEADCODE, 
    SL, ADDEDBY, ADD_COMP_NAME, ADD_IPADD, ADD_OSUSER, 
    UPD_COMP_NAME, UPD_IPADD, UPD_OSUSER, UPDATEDDATE, UPDATEDBY, 
    SCALE, AMT_B4_F, AMT_AFTER_F, AMT_2B4_F)
 Values
   (57, 'IPI-007001', 2020, NULL, TO_DATE('20/Dec/20', 'DD/MON/YY'), 
    'P.F. Contribution', 'GRADE-13', 2416, 2416, 2415, 
    '057', NULL, '2', NULL, '057', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 1718, 2030, 1612);
Insert into HR_EMPSALSTRUCTURE
   (SLNO, EMPCODE, YEAROFSTRUC, EDATE, TRNDATE, 
    PARTICULAR, DESIGCODE, AMOUNTPRV, AMOUNTCUR, SALPER, 
    REFNO, YEARMN, PRTCLR_TYPE, PTC_FLAT, HEADCODE, 
    SL, ADDEDBY, ADD_COMP_NAME, ADD_IPADD, ADD_OSUSER, 
    UPD_COMP_NAME, UPD_IPADD, UPD_OSUSER, UPDATEDDATE, UPDATEDBY, 
    SCALE, AMT_B4_F, AMT_AFTER_F, AMT_2B4_F)
 Values
   (13, 'IPI-007001', 2020, NULL, TO_DATE('20/Dec/20', 'DD/MON/YY'), 
    'Co''S  Con. To Pf', 'GRADE-13', 1080, 1208, 1208, 
    '013', NULL, '1', NULL, '013', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 859, 1015, 806);
Insert into HR_EMPSALSTRUCTURE
   (SLNO, EMPCODE, YEAROFSTRUC, EDATE, TRNDATE, 
    PARTICULAR, DESIGCODE, AMOUNTPRV, AMOUNTCUR, SALPER, 
    REFNO, YEARMN, PRTCLR_TYPE, PTC_FLAT, HEADCODE, 
    SL, ADDEDBY, ADD_COMP_NAME, ADD_IPADD, ADD_OSUSER, 
    UPD_COMP_NAME, UPD_IPADD, UPD_OSUSER, UPDATEDDATE, UPDATEDBY, 
    SCALE, AMT_B4_F, AMT_AFTER_F, AMT_2B4_F)
 Values
   (15, 'IPI-007001', 2020, NULL, TO_DATE('20/Dec/20', 'DD/MON/YY'), 
    'Dearness Allowance', 'GRADE-13', NULL, 1208, 0, 
    '015', NULL, '1', NULL, '015', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 2000, NULL, NULL);
Insert into HR_EMPSALSTRUCTURE
   (SLNO, EMPCODE, YEAROFSTRUC, EDATE, TRNDATE, 
    PARTICULAR, DESIGCODE, AMOUNTPRV, AMOUNTCUR, SALPER, 
    REFNO, YEARMN, PRTCLR_TYPE, PTC_FLAT, HEADCODE, 
    SL, ADDEDBY, ADD_COMP_NAME, ADD_IPADD, ADD_OSUSER, 
    UPD_COMP_NAME, UPD_IPADD, UPD_OSUSER, UPDATEDDATE, UPDATEDBY, 
    SCALE, AMT_B4_F, AMT_AFTER_F, AMT_2B4_F)
 Values
   (75, 'IPI-007001', 2020, NULL, TO_DATE('20/Dec/20', 'DD/MON/YY'), 
    'Superannuation Fund', 'GRADE-13', NULL, 200, 200, 
    '075', NULL, '2', NULL, '075', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL);
Insert into HR_EMPSALSTRUCTURE
   (SLNO, EMPCODE, YEAROFSTRUC, EDATE, TRNDATE, 
    PARTICULAR, DESIGCODE, AMOUNTPRV, AMOUNTCUR, SALPER, 
    REFNO, YEARMN, PRTCLR_TYPE, PTC_FLAT, HEADCODE, 
    SL, ADDEDBY, ADD_COMP_NAME, ADD_IPADD, ADD_OSUSER, 
    UPD_COMP_NAME, UPD_IPADD, UPD_OSUSER, UPDATEDDATE, UPDATEDBY, 
    SCALE, AMT_B4_F, AMT_AFTER_F, AMT_2B4_F)
 Values
   (25, 'IPI-007001', 2020, NULL, TO_DATE('20/Dec/20', 'DD/MON/YY'), 
    'Other Allowance', 'GRADE-13', NULL, 0, 0, 
    '025', NULL, '1', NULL, '025', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL);
Insert into HR_EMPSALSTRUCTURE
   (SLNO, EMPCODE, YEAROFSTRUC, EDATE, TRNDATE, 
    PARTICULAR, DESIGCODE, AMOUNTPRV, AMOUNTCUR, SALPER, 
    REFNO, YEARMN, PRTCLR_TYPE, PTC_FLAT, HEADCODE, 
    SL, ADDEDBY, ADD_COMP_NAME, ADD_IPADD, ADD_OSUSER, 
    UPD_COMP_NAME, UPD_IPADD, UPD_OSUSER, UPDATEDDATE, UPDATEDBY, 
    SCALE, AMT_B4_F, AMT_AFTER_F, AMT_2B4_F)
 Values
   (34, 'IPI-007001', 2020, NULL, TO_DATE('20/Dec/20', 'DD/MON/YY'), 
    'City Allowance', 'GRADE-13', NULL, 0, 0, 
    '034', 202008, '1', NULL, '034', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 600, NULL, NULL);
Insert into HR_EMPSALSTRUCTURE
   (SLNO, EMPCODE, YEAROFSTRUC, EDATE, TRNDATE, 
    PARTICULAR, DESIGCODE, AMOUNTPRV, AMOUNTCUR, SALPER, 
    REFNO, YEARMN, PRTCLR_TYPE, PTC_FLAT, HEADCODE, 
    SL, ADDEDBY, ADD_COMP_NAME, ADD_IPADD, ADD_OSUSER, 
    UPD_COMP_NAME, UPD_IPADD, UPD_OSUSER, UPDATEDDATE, UPDATEDBY, 
    SCALE, AMT_B4_F, AMT_AFTER_F, AMT_2B4_F)
 Values
   (1, 'IPI-007001', 2020, NULL, TO_DATE('15/Feb/20', 'DD/MON/YY'), 
    'Basic Salary', 'GRADE-13', 10800, 12075, 12075, 
    '1', 202002, '1', NULL, '001', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 8590, 10150, 8060);
Insert into HR_EMPSALSTRUCTURE
   (SLNO, EMPCODE, YEAROFSTRUC, EDATE, TRNDATE, 
    PARTICULAR, DESIGCODE, AMOUNTPRV, AMOUNTCUR, SALPER, 
    REFNO, YEARMN, PRTCLR_TYPE, PTC_FLAT, HEADCODE, 
    SL, ADDEDBY, ADD_COMP_NAME, ADD_IPADD, ADD_OSUSER, 
    UPD_COMP_NAME, UPD_IPADD, UPD_OSUSER, UPDATEDDATE, UPDATEDBY, 
    SCALE, AMT_B4_F, AMT_AFTER_F, AMT_2B4_F)
 Values
   (5, 'IPI-007001', 2020, NULL, TO_DATE('15/Feb/20', 'DD/MON/YY'), 
    'House Rent', 'GRADE-13', 8101, 9056, 9056, 
    '5', 202002, '1', NULL, '005', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 6444, 7613, 6046);
Insert into HR_EMPSALSTRUCTURE
   (SLNO, EMPCODE, YEAROFSTRUC, EDATE, TRNDATE, 
    PARTICULAR, DESIGCODE, AMOUNTPRV, AMOUNTCUR, SALPER, 
    REFNO, YEARMN, PRTCLR_TYPE, PTC_FLAT, HEADCODE, 
    SL, ADDEDBY, ADD_COMP_NAME, ADD_IPADD, ADD_OSUSER, 
    UPD_COMP_NAME, UPD_IPADD, UPD_OSUSER, UPDATEDDATE, UPDATEDBY, 
    SCALE, AMT_B4_F, AMT_AFTER_F, AMT_2B4_F)
 Values
   (7, 'IPI-007001', 2020, NULL, TO_DATE('15/Feb/20', 'DD/MON/YY'), 
    'Conveyance  Allow', 'GRADE-13', 2200, 2200, 2200, 
    '7', 202002, '1', NULL, '007', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 1500, 2200, 1500);
Insert into HR_EMPSALSTRUCTURE
   (SLNO, EMPCODE, YEAROFSTRUC, EDATE, TRNDATE, 
    PARTICULAR, DESIGCODE, AMOUNTPRV, AMOUNTCUR, SALPER, 
    REFNO, YEARMN, PRTCLR_TYPE, PTC_FLAT, HEADCODE, 
    SL, ADDEDBY, ADD_COMP_NAME, ADD_IPADD, ADD_OSUSER, 
    UPD_COMP_NAME, UPD_IPADD, UPD_OSUSER, UPDATEDDATE, UPDATEDBY, 
    SCALE, AMT_B4_F, AMT_AFTER_F, AMT_2B4_F)
 Values
   (10, 'IPI-007001', 2020, NULL, TO_DATE('15/Feb/20', 'DD/MON/YY'), 
    'Medical Allowance', 'GRADE-13', 2000, 2000, 2000, 
    '10', 202002, '1', NULL, '010', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 1500, 2000, 1500);
Insert into HR_EMPSALSTRUCTURE
   (SLNO, EMPCODE, YEAROFSTRUC, EDATE, TRNDATE, 
    PARTICULAR, DESIGCODE, AMOUNTPRV, AMOUNTCUR, SALPER, 
    REFNO, YEARMN, PRTCLR_TYPE, PTC_FLAT, HEADCODE, 
    SL, ADDEDBY, ADD_COMP_NAME, ADD_IPADD, ADD_OSUSER, 
    UPD_COMP_NAME, UPD_IPADD, UPD_OSUSER, UPDATEDDATE, UPDATEDBY, 
    SCALE, AMT_B4_F, AMT_AFTER_F, AMT_2B4_F)
 Values
   (37, 'IPI-007001', 2020, NULL, TO_DATE('15/Feb/20', 'DD/MON/YY'), 
    'Allowance', 'GRADE-13', 2800, 2800, 3000, 
    '37', 202002, '1', NULL, '037', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 2500, 2800, 2500);
Insert into HR_EMPSALSTRUCTURE
   (SLNO, EMPCODE, YEAROFSTRUC, EDATE, TRNDATE, 
    PARTICULAR, DESIGCODE, AMOUNTPRV, AMOUNTCUR, SALPER, 
    REFNO, YEARMN, PRTCLR_TYPE, PTC_FLAT, HEADCODE, 
    SL, ADDEDBY, ADD_COMP_NAME, ADD_IPADD, ADD_OSUSER, 
    UPD_COMP_NAME, UPD_IPADD, UPD_OSUSER, UPDATEDDATE, UPDATEDBY, 
    SCALE, AMT_B4_F, AMT_AFTER_F, AMT_2B4_F)
 Values
   (120, 'IPI-007001', NULL, NULL, NULL, 
    'MC Risk Compensation Ploicy', NULL, NULL, 200, 0, 
    '120', NULL, '2', NULL, '120', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, 'WAFI', 
    NULL, NULL, NULL, NULL);
COMMIT;
